EightfoldAI/octuple

.husky/commit-msg, commitlint.config.js
Configures commitlint for yarn, adds config file to better manage rules.
=> fix: commitlint: adds custom commitlint config

src/components/Pills/Pill.tsx
Fixes break by removing unused selectors
=> fix: pills: removes unused selectors

src/components/Button/button.module.scss, src/components/Icon/Icon.types.ts, src/components/Inputs/input.module.scss, src/components/Pills/pills.module.scss, src/styles/components/_dialogs.scss, src/styles/components/_info-bars.scss, src/styles/components/_menus.scss, src/styles/components/_modals.scss, src/styles/components/_paginations.scss, src/styles/components/_panels.scss, src/styles/components/_snackbars.scss, src/styles/themes/_definitions-light.scss
limit rems to font sizes and line heights only
=> chore: rem: tidy up rem usage

package.json, src/__snapshots__/storybook.test.js.snap, src/storybook.test.js, yarn.lock
Setting up plugin and adding auto generated snapshot testing via storybook stories
=> chore: add snapshot testing

src/components/Button/button.module.scss, src/styles/base/_typography.scss
=> fix: button: move unreferenced global style into the module

global.d.ts, src/components/Button/button.module.scss, src/components/ConfigProvider/A11y/A11y.types.ts, src/components/ConfigProvider/A11y/index.ts, src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/ConfigProvider/ConfigProvider.tsx, src/components/ConfigProvider/ConfigProvider.types.ts, src/components/Inputs/input.module.scss, src/components/Label/Label.tsx, src/components/Label/Label.types.ts, src/hooks/navigator.d.ts, src/hooks/useCanvasDirection.test.tsx, src/hooks/useCanvasDirection.ts, src/hooks/useFocusVisible.test.tsx, src/hooks/useFocusVisible.ts, src/hooks/useFocusVisibleClassName.test.tsx, src/hooks/useFocusVisibleClassName.ts, src/styles/themes/_definitions-light.scss
Adds mouse vs keyboard detection and BiDi hooks, updates ConfigProvider to consume useFocusVisible hook to enable accessible styling.
=> feat: accessibility and i18n: adds keyboard focus, canvas direction support

src/components/Inputs/TextInput/TextInput.tsx
fixes bug where number inputs accepted a text char
=> fix: text input: hides clear button for number inputs

src/__snapshots__/storybook.test.js.snap, src/components/Pagination/Pager.tsx, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/Pagination.types.ts, src/components/Pagination/index.ts, src/components/Pagination/pagination.module.scss, src/hooks/useSingleton.ts, src/octuple.ts
Jira Ticket:
[ENG-2790: [Octuple] Pagination Component Suite](https://eightfoldai.atlassian.net/browse/ENG-2790)
=> feat: pagination: adds pagination component

src/hooks/useOnClickOutside.ts
Fix for click on menu item not working intermittently
=> fix: click on menu item not working intermittently

src/components/Avatar/Avatar.stories.tsx, src/components/Avatar/Avatar.tsx, src/components/Avatar/Avatar.types.ts, src/components/Avatar/avatar.module.scss, src/components/Avatar/index.ts, src/octuple.ts
=> feat: added avatar component

src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/components/Link/Link.types.ts, src/components/Link/index.ts, src/components/Link/link.module.scss, src/octuple.ts
=> feat: added link component

src/__snapshots__/storybook.test.js.snap
adds missing snapshot ahead of v1.5.0 release
=> chore: jest: add link snapshot

src/components/Pagination/pagination.module.scss
The dots text was misaligned, this change fixes it.
=> chore: pagination: adjusts text layout of dot buttons

src/octuple.ts
Adds missed exports ahead of v1.5.1 release
=> fix: exports: adds stack and selectors to exports

src/components/Modal/Modal.tsx
fix styling of modal header
https://eightfoldai.atlassian.net/browse/ENG-18898
Modal header should be bolder and inline with the design
=> fix: modal: fix styling of modal header

src/components/Accordion/Accordion.tsx
accordion body classnames placement
=> chore: accordion body classnames placement

src/components/Accordion/Accordion.tsx, src/components/Accordion/accordion.module.scss, src/components/Icon/Icon.tsx
=> chore: accordion and icon changes

src/components/Button/button.module.scss
Updates buttons to use primary color instead of 70% hue.
ENG-20425
Pull PR and run locally the changes, verify the colors of button [using local host](http://localhost:2022/?path=/story/config-provider--theming)
=> fix: button: update default color scheme to use primary

.github/workflows/build.yml
=> chore: make ci builds run on main next

src/__snapshots__/storybook.test.js.snap, src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Dialog/BaseDialog/BaseDialog.types.ts, src/components/Dialog/Dialog.stories.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/Modal.types.ts, src/components/Modal/modal.module.scss, src/components/Panel/Panel.tsx, src/hooks/useScrollLock.test.tsx, src/hooks/useScrollLock.ts, src/styles/abstracts/_mixins.scss
=> fix: handle onScrollLock cleanly, dialog to render inside parent element

src/components/Inputs/TextInput/TextInput.tsx
fix: fixed search event persist issue
=> fix: fixed search event persist issue

src/components/Modal/modal.module.scss
modal: disable scroll in body on x axis
=> fix: modal: disable scroll in body on x axis

src/__snapshots__/storybook.test.js.snap, src/components/Selectors/RadioButton/RadioButton.tsx
Adds classNames prop to RadioButton component
ENG-13961
Verify the classNames prop exists by passing a className to RadioButton
=> fix: radio button: add classnames prop to radio button

src/components/ConfigProvider/ConfigProvider.stories.tsx
=> chore: remove unused var

src/components/Pagination/Pagination.tsx
Fixes the page to use the page set by the event handler
ENG-13961
Use the jumper and ensure the page updates
=> fix: pagination: ensure jumper applies current page

src/__snapshots__/storybook.test.js.snap, src/components/Button/BaseButton.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.types.ts, src/components/Button/DefaultButton/DefaultButton.tsx, src/components/Button/NeutralButton/NeutralButton.tsx, src/components/Button/PrimaryButton/PrimaryButton.tsx, src/components/Button/SecondaryButton/SecondaryButton.tsx, src/components/Button/TwoStateButton/TwoStateButton.stories.tsx, src/components/Button/TwoStateButton/TwoStateButton.tsx, src/components/Button/button.module.scss
Adds counter badge to button
ENG-13961
Pull the changes and verify the counter exists in the relevant stories:
Button
> Counter
> Toggle With Counter
> Split With Counter
=> feat: button: adds counter badge support to all buttons

src/__snapshots__/storybook.test.js.snap, src/components/Avatar/Avatar.tsx, src/components/Avatar/avatar.module.scss, src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/pills.module.scss
feat: add all theme2 colors to avatar and pill component
=> feat: add all theme2 colors to avatar and pill component

.github/workflows/build.yml, .github/workflows/npm-publish.yml
chore: update github pages on ocutple release
https://eightfoldai.atlassian.net/browse/ENG-22091
=> chore: update github pages on octuple release

src/components/Snackbar/Snackbar.test.tsx
https://eightfoldai.atlassian.net/browse/ENG-21757
=> chore: update snackbar tests to use fake timers

src/components/Accordion/accordion.module.scss, src/components/Button/button.module.scss, src/components/Inputs/input.module.scss
fix: fix interaction bugs in input, accordion and buttons
https://eightfoldai.atlassian.net/browse/ENG-22197
https://eightfoldai.atlassian.net/browse/ENG-22196
https://eightfoldai.atlassian.net/browse/ENG-22192
https://eightfoldai.atlassian.net/browse/ENG-22191
https://eightfoldai.atlassian.net/browse/ENG-22190
https://eightfoldai.atlassian.net/browse/ENG-22194
https://eightfoldai.atlassian.net/browse/ENG-22193
=> fix: interaction bugs in input, accordion and buttons

src/components/Inputs/TextArea/TextArea.stories.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.stories.tsx, src/components/Inputs/TextInput/TextInput.tsx
Fixing value prop for text input & text area
=> Fixing value prop for text input & text area

src/components/Button/button.module.scss
fix: update button font sizes and outline colors
https://eightfoldai.atlassian.net/browse/ENG-22832
=> fix: update button font sizes and outline colors

src/__snapshots__/storybook.test.js.snap, src/components/Button/Button.stories.tsx, src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/List/List.stories.tsx, src/components/List/List.tsx, src/components/List/List.types.ts, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.tsx, src/components/Menu/Menu.types.ts, src/components/Menu/MenuItem/MenuItem.tsx, src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/menuItem.module.scss, src/components/Pagination/Pagination.tsx, src/components/Select/Select.types.ts, src/octuple.ts
fix: remove buttons from menu item
skip
=> fix: remove buttons from menu item

.github/workflows/npm-publish.yml, package.json
chore: setup prerelease workflow
=> chore: setup prerelease workflow

.github/workflows/npm-publish.yml
chore: publish only on a release
=> chore: publish only on a release

src/components/Pagination/Pager.tsx, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/Pagination.types.ts, src/components/Pagination/pagination.module.scss, src/components/PersistentBar/PersistentBar.stories.tsx, src/components/PersistentBar/PersistentBar.tsx, src/components/PersistentBar/PersistentBar.types.ts, src/components/PersistentBar/index.ts, src/components/PersistentBar/persistentBar.module.scss, src/styles/themes/_definitions-light.scss
[Persistent Bar] As a developer I should be able to use the Octuple Persistent Bar component in my project
https://eightfoldai.atlassian.net/browse/ENG-2818
https://eightfoldai.atlassian.net/browse/ENG-22904
=> [Persistent Bar] As a developer I should be able to use the Octuple Persistent Bar component in my project

.github/workflows/npm-publish.yml, CHANGELOG.md, package.json
chore: fix npm publish command
=> chore: fix npm publish command

src/octuple.ts
Export persistent bar in octuple.ts
=> Export persistent bar in octuple.ts

src/components/Button/button.module.scss, src/components/ConfigProvider/ConfigProvider.stories.tsx
fix: update two state button to theme 2
https://eightfoldai.atlassian.net/browse/ENG-23848
=> fix: update two state button to theme 2

src/components/PersistentBar/persistentBar.module.scss
debugging slack action
NA
Verify slack action succeeds
=> feat: add persistent bar

src/__snapshots__/storybook.test.js.snap, src/components/Table/Internal/Header/Header.tsx, src/components/Table/Internal/Header/Header.types.ts, src/components/Table/Internal/Header/HeaderRow.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.stories.tsx
feat: add ability to pass custom class to table header
=> feat: add ability to pass custom class to table header

src/octuple.ts
exports DatePicker and TimePicker components
ENG-2796
NA
=> chore: datetimepicker: export date and time picker

src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.stories.tsx, src/components/Inputs/TextArea/TextArea.stories.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.stories.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/components/Inputs/input.module.scss
Adds underline Input shape and disabled styles, updates theme 1 styles to the latest.
ENG-24330
TODO: Need to add UTs for Inputs in future change
Pull the pr branch, run `yarn storybook` and verify the prop changes:
- allowDisabledFocus
- disabled
- shape: Underline
=> feat: input: add underline variant

src/components/Dropdown/Dropdown.tsx
fix: Toggle hover dropdown on click, fixed dropdown flicker on close
[ENG-24565](https://eightfoldai.atlassian.net/browse/ENG-24565)
=> fix: toggle hover dropdown on click, fixed dropdown flicker on close

src/__snapshots__/storybook.test.js.snap
=> chore: test: update snapshots

src/__snapshots__/storybook.test.js.snap
Resolve conflicts with latest main
ENG-24364
NA
=> chore: test: resolve conflicts

src/components/Select/Select.tsx, src/components/Select/Select.types.ts
filter custom function
https://eightfoldai.atlassian.net/browse/ENG-22418
skip
=> ENG-22418 | feat: added filter options

src/octuple.ts
=> fix: export TextInputSize

src/components/Accordion/accordion.module.scss, src/components/Table/Internal/octable.module.scss, src/components/Table/Styles/table.module.scss
feat: table: update table hover color, fix accordion hover overflow
=> feat: table: update table hover color, fix accordion hover overflow

src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Dialog/BaseDialog/BaseDialog.types.ts, src/components/Dialog/Dialog.tsx, src/components/Modal/Modal.tsx, src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Panel/Panel.types.ts, src/components/Panel/panel.module.scss, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.tsx, src/src/components/Panel/__snapshots__/Panel.stories.storyshot, src/src/components/RadioButton/__snapshots__/RadioButton.stories.storyshot
merge latest main into main-next
=> chore: merge latest into main next

.gitattributes, .husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push
uninstall git lfs
- removes hooks
- removes gitattributes
=> chore: uninstall git lfs

src/components/DateTimePicker/DatePicker/Tests/__snapshots__/QuarterPicker.test.js.snap, src/components/DateTimePicker/DatePicker/Tests/__snapshots__/RangePicker.test.js.snap, src/components/DateTimePicker/DatePicker/Tests/__snapshots__/WeekPicker.test.js.snap, src/components/DateTimePicker/Internal/Tests/__snapshots__/picker.test.tsx.snap, src/components/DateTimePicker/Internal/Tests/__snapshots__/range.test.tsx.snap, src/components/DateTimePicker/TimePicker/Tests/__snapshots__/index.test.js.snap, src/components/Table/Internal/Tests/__snapshots__/Summary.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.expand.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.filter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.test.js.snap, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/Tree.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/TreeNodeProps.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/TreeProps.test.tsx.snap
removes cached lfs files, adds them back to project
=> chore: removes cached lfs files and adds them back

.gitattributes, .husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-push, src/components/DateTimePicker/DatePicker/Tests/__snapshots__/QuarterPicker.test.js.snap, src/components/DateTimePicker/DatePicker/Tests/__snapshots__/RangePicker.test.js.snap, src/components/DateTimePicker/DatePicker/Tests/__snapshots__/WeekPicker.test.js.snap, src/components/DateTimePicker/Internal/Tests/__snapshots__/picker.test.tsx.snap, src/components/DateTimePicker/Internal/Tests/__snapshots__/range.test.tsx.snap, src/components/DateTimePicker/TimePicker/Tests/__snapshots__/index.test.js.snap, src/components/Table/Internal/Tests/__snapshots__/Summary.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.expand.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.filter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.test.js.snap, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/Tree.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/TreeNodeProps.test.tsx.snap, src/components/Tree/Internal/tests/__snapshots__/TreeProps.test.tsx.snap
cherry picks latest main into main-next ahead of consolidation.
=> chore: cherry pick latest main no lfs snaps into main-next

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts
feat: tooltip: allow passing custom class and style to tooltip wrapper
=> feat: tooltip: allow passing custom class and style to tooltip wrapper

clean-package.config.json, package.json, yarn.lock
chore: remove development configuration before publishing package
=> chore: remove development configuration before publishing package

src/components/CheckBox/CheckBox.stories.tsx, src/components/CheckBox/CheckBox.test.tsx, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/CheckBoxGroup.tsx, src/components/CheckBox/Checkbox.types.ts, src/components/CheckBox/ToggleSwitch.stories.tsx, src/components/CheckBox/checkbox.module.scss, src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/RadioButton/Radio.types.ts, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/RadioGroup.tsx, src/components/RadioButton/radio.module.scss, src/components/Table/Tests/__snapshots__/Table.fixselectionexpandonleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionwithcols.shot, src/components/Table/Tests/__snapshots__/Table.usecolselectionwithkey.shot, src/octuple.ts, src/src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/src/components/CheckBox/__snapshots__/ToggleSwitch.stories.storyshot, src/src/components/ConfigProvider/__snapshots__/ConfigProvider.stories.storyshot, src/src/components/RadioButton/__snapshots__/RadioButton.stories.storyshot, src/src/components/Table/__snapshots__/Table.stories.storyshot, src/styles/themes/_definitions-light.scss
updates snaps and adds labelPosition (`Start` and `End`) prop to selectors.
https://user-images.githubusercontent.com/99700808/181125010-1a816f7b-6c94-4cc3-992a-def0006a9f54.mp4
ENG-22184
Pull the the pr branch and run `yarn`, then `yarn storybook` verify the Toggle Switch story
=> feat: toggle: add toggle switch

package.json
chore: change package cleanup to pre and post publish
=> chore: change package cleanup to pre and post publish

src/components/Snackbar/snackbar.module.scss, src/styles/themes/_definitions-light.scss
fix: snackbar: increase snackbar z-index to be more than surface elements
https://eightfoldai.atlassian.net/browse/ENG-22772
=> fix: snackbar: increase snackbar z-index to be more than surface elements

src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.types.ts, src/components/Button/SplitButton/SplitButton.tsx, src/components/Button/SystemUIButton/SystemUIButton.tsx, src/components/Button/button.module.scss, src/components/Button/index.ts, src/octuple.ts, src/src/components/Button/__snapshots__/Button.stories.storyshot, src/src/components/Icon/__snapshots__/Icon.stories.storyshot
Adds System UI Button
Spec --> https://www.figma.com/file/SlKRC7oKF7XZyHMv2op4ch/Octuple-DS-(Theme-2)?node-id=292%3A711
https://user-images.githubusercontent.com/99700808/182242145-5011081c-bff5-4bea-a87c-15071c4a1040.mp4
ENG-26009
Pull the pr changes and then do `yarn` and `yarn storybook`, verify the System UI story under Button, or implement a `SystemUIButton` using CodeSandbox CI and verify.
=> feat: system ui button: add system ui button

src/components/MatchScore/MatchScore.tsx
https://eightfoldai.atlassian.net/browse/ENG-24391
https://eightfoldai.atlassian.net/browse/ENG-24388
=> fix: match score: update logic for filled and half filled scores

.github/workflows/npm-publish.yml, clean-package.config.json, package.json, yarn.lock
maintenance task, unblocks teams that need to install latest theme 1 package
NA
pull pr branch and run `yarn`, then `yarn storybook`. Verify each story behaves as expected.
=> chore: cherry pick and port bug fixes from main

src/components/Inputs/input.module.scss
maintenance task, unblocks teams that need to install latest theme 1 package (with a valid fix message)
NA
pull pr branch and run `yarn`, then `yarn storybook`. Verify each story behaves as expected.
=> fix: package: fixes package install by cherry picking from main

src/components/Navbar/navbar.module.scss, src/styles/abstracts/_mixins.scss
(cherry picked from commit 4a4e60cd2804dfef7967c48f38f7ef937ef831eb)
=> fix: navbar: apply scoped css resets to navbar component (#288)

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/select.module.scss, src/src/components/Select/__snapshots__/Select.stories.storyshot
maintenance task, cherry-pick critical fix from main
=> fix: select: cherry-pick fixes select clear when items are toggled from main

src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/radio.module.scss
selectors: fix selectors getting squished in certain scenarios
https://eightfoldai.atlassian.net/browse/ENG-26332
=> fix: selectors: fix selectors getting squished in certain scenarios

src/octuple.ts
fix: select: export SelectShape and SelectSize
=> fix: select: export SelectShape and SelectSize

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/components/Tooltip/tooltip.module.scss, src/octuple.ts
feat: tooltip: add sizes to tooltip
=> feat: tooltip: add sizes to tooltip

src/components/Button/button.module.scss, src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/radio.module.scss
adds fix to size modifiers
https://eightfoldai.atlassian.net/browse/ENG-26332
=> fix: selectors: fix selectors getting squished in certain scenarios part two

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/tooltip.module.scss, src/src/components/Inputs/SearchBox/__snapshots__/SearchBox.stories.storyshot, src/src/components/Inputs/TextArea/__snapshots__/TextArea.stories.storyshot, src/src/components/Inputs/TextInput/__snapshots__/TextInput.stories.storyshot, src/src/components/Label/__snapshots__/Label.stories.storyshot, src/src/components/Table/__snapshots__/Table.stories.storyshot, src/src/components/Tooltip/__snapshots__/Tooltip.stories.storyshot
=> fix: safari tooltip disabled element fixes

src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/components/Pagination/Pagination.tsx
fix: change default input and textarea shape to rectangle
=> fix: change default input and textarea shape to rectangle

.github/workflows/npm-publish.yml, package.json
chore: fix storybook build static directory
skip
=> chore: fix storybook build static directory

src/components/Menu/Menu.tsx, src/components/Menu/MenuItem/MenuItemSubHeader/MenuItemSubHeader.tsx, src/components/Menu/MenuItem/menuItem.module.scss, src/components/Menu/menu.module.scss, src/src/components/Button/__snapshots__/Button.stories.storyshot, src/styles/abstracts/_mixins.scss
fix: menu: remove octuple chrome from menu and menu item
=> fix: menu: remove octuple chrome from menu and menu item

src/components/Table/Internal/octable.module.scss, src/styles/themes/_definitions.scss
fix: table: remove let border from last fixed cell
=> fix: table: remove left border from last fixed cell

src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/radio.module.scss
fix: selectors: increase radio and checkbox paddings
=> fix: selectors: increase radio and checkbox paddings

.storybook/main.js, package.json, yarn.lock
chore: add a11y plugin to storybook
=> chore: add a11y plugin to storybook

src/components/Panel/index.ts, src/octuple.ts
=> fix: exporting header

src/components/Dropdown/dropdown.module.scss, src/components/Menu/MenuItem/menuItem.module.scss
fix: menu: update menu min width and reduce font weight of menu item
skip
=> fix: menu: update menu min width and reduce font weight of menu item

src/components/Inputs/input.module.scss
fix: text input color
The text input value(text) appeared to be similar to placeholder. Changing the cooler from var(--grey-color-60) to var(--text-primary-color)
1. skip
=> fix: text input color

src/components/Table/Styles/table.module.scss
fix: increase border radius to 24px
Increasing border radius from 8px to 24px
1. Skip
=> fix: table: increase border radius

src/components/Stack/Stack.types.ts, src/components/Stack/stack.module.scss
=> fix: stack: add ml size

src/components/Pills/pills.module.scss
fix: pills: fix allignment of text
=> fix: pills: fix allignment of text

src/components/Table/Styles/mixins.scss
fix: table: remove box shadow from bordered table
=> fix: table: remove box shadow from bordered table

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx
fix: dropdown: fix on click outside getting triggered on portaled dropdowns
=> fix: dropdown: fix on click outside getting triggered on portaled dropdowns

src/components/Empty/empty.module.scss, src/components/Table/Internal/octable.module.scss, src/components/Table/Styles/table.module.scss, src/styles/themes/_default-theme.scss
fix: update styles for table header and empty component
=> fix: update styles for table header and empty component

src/components/CheckBox/Checkbox.types.ts, src/components/ConfigProvider/A11y/A11y.types.ts, src/components/ConfigProvider/ConfigProvider.types.ts, src/components/DateTimePicker/DatePicker/Generate/Generate.types.tsx, src/components/DateTimePicker/Internal/OcPicker.types.ts
Adds missing type annotations and cleans them up. Also cleans up some other component type annotations.
ENG-28724
N/A
pull the pr branch and do `yarn` and then `yarn storybook`, verify the DatePicker stories.
=> fix: date picker: adds type annotations and alphabetizes types

src/components/CheckBox/CheckBox.stories.tsx, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/CheckBoxGroup.tsx, src/components/CheckBox/Checkbox.types.ts, src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/Radio.types.ts, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/RadioGroup.tsx, src/components/RadioButton/radio.module.scss, src/octuple.ts
feat: selectors: add ability to vertically align label
https://eightfoldai.atlassian.net/browse/ENG-27740
skip
=> feat: selectors: add ability to vertically align label

src/components/Table/Internal/octable.module.scss
fix: remove table data text overflow
=> fix: remove table data text overflow

src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Skeleton/Skeleton.types.ts, src/components/Skeleton/index.ts, src/components/Skeleton/skeleton.module.scss, src/octuple.ts
feat: add skeleton component
https://user-images.githubusercontent.com/95337653/189269100-4419ce69-1587-4d6f-b734-2eb0d4f1fb31.mov
https://eightfoldai.atlassian.net/browse/ENG-2829
skip
=> feat: add skeleton component

src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Dialog/BaseDialog/base-dialog.module.scss, src/hooks/useScrollShadows.ts
=> feat: dialog: add box shadows on scrollable content for modals, dialogs

src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/radio.module.scss, src/hooks/useScrollShadows.ts
fix: selectors: add minor paddding in start align
=> fix: selectors: add minor paddding in start align

src/components/Dialog/Dialog.stories.tsx, src/components/Dialog/DialogHelper.tsx, src/components/Dialog/dialog.module.scss, src/components/Dialog/index.ts, src/octuple.ts
feat: dialog: add dialog helper method to render dialogs with ease
=> feat: dialog: add dialog helper method to render dialogs with ease

src/components/ConfigProvider/ConfigProvider.types.ts
Enables TypeScript implementations.
=> fix: config provider: export children prop type

src/components/DateTimePicker/DatePicker/DatePicker.stories.tsx, src/components/DateTimePicker/DatePicker/Generate/generateRangePicker.tsx, src/components/DateTimePicker/DatePicker/Generate/generateSinglePicker.tsx, src/components/DateTimePicker/DatePicker/datepicker.module.scss, src/components/DateTimePicker/Internal/OcPicker.tsx, src/components/DateTimePicker/Internal/OcPicker.types.ts, src/components/DateTimePicker/Internal/OcRangePicker.tsx, src/components/DateTimePicker/Internal/Tests/partial.test.tsx, src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/DateTimePicker/TimePicker/Tests/__snapshots__/index.test.js.snap, src/components/DateTimePicker/TimePicker/TimePicker.stories.tsx, src/components/LocaleProvider/index.tsx, src/src/components/DateTimePicker/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/src/components/DateTimePicker/TimePicker/__snapshots__/TimePicker.stories.storyshot, src/src/components/Form/__snapshots__/Form.stories.storyshot, src/src/components/Icon/__snapshots__/Icon.stories.storyshot
Adds `TimePicker` story, fixes bordered prop of the pickers, updates DatPicker stories and adds loc support via the LocaleReceiver
https://user-images.githubusercontent.com/99700808/190237489-dc33ac0b-d1e2-4df1-8704-55be4d5c6874.mp4
ENG-29523
pull the pr branch and do `yarn` and `yarn storybook`. Verify the TimePicker and DatePicker stories behave as expected.
=> feat: picker: add time picker story and loc string support to pickers

src/components/Link/Link.stories.tsx
Adjusts storybook story according to new link layout.
=> fix: link: updates link story layout to account for link style flex removal

package.json, src/components/ConfigProvider/Theming/themes.ts, src/components/Form/Form.stories.tsx, src/components/Inputs/SearchBox/SearchBox.stories.tsx, src/components/Link/link.module.scss, src/components/Navbar/Navbar.stories.tsx, src/components/Table/Hooks/useSorter.tsx, src/components/Table/Internal/octable.module.scss, src/components/Table/Styles/bordered.scss, src/components/Table/Styles/table.module.scss, src/components/Table/Tests/__snapshots__/empty.renderloading.shot, src/components/Tree/Tests/__snapshots__/index.loadingicon.shot, src/styles/themes/_default-theme.scss, src/styles/themes/_definitions.scss, yarn.lock
Fixes a bug where two horizontal scrollbars sometimes appear in table
Fixes a Table header sort tooltip occlusion by adding portal prop
Fixes spinner animation by upgrading the mdi package to latest
Patches Slider behavior in Form story
Updates SearchBox size to the correct default in its story
Renames Navbar stories
ENG-30345
ENG-30344
ENG-30346
Pull the pr branch and do `yarn` and `yarn storybook`. Test the `Navbar`, `Table`, `SearchBox` stories and the `Slider` in `Form` Disabled story
=> fix: theme: fixes navbar and tabs configprovider theme

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/Accordion.types.ts, src/components/Accordion/accordion.module.scss, src/components/Badge/badge.module.scss, src/octuple.ts
feat: add shape and size prop for accordion
https://eightfoldai.atlassian.net/browse/ENG-24749
=> feat: add shape and size prop for accordion

src/components/Card/Card.stories.tsx, src/components/Card/Card.test.tsx, src/components/Card/Card.tsx, src/components/Card/Card.types.ts, src/components/Card/card.module.scss, src/components/Card/index.ts, src/octuple.ts
Create Card component for Octuple:
Base Card:
Custom Card: 
https://eightfoldai.atlassian.net/browse/ENG-28741
=> Initial implementation of the Card component for Octuple

src/components/Card/Card.stories.tsx
Custom card UI Polish
N/A
-  [X] Bugfix Pull Request
Pull the pr branch and run `yarn` and `yarn storybook`. Test the `Card` `Custom Card` story and verify it behaves as expected.
=> fix: card: custom card story ui polish

src/components/Dropdown/Dropdown.tsx, src/hooks/useAccessibility.ts
- fixing focus issue in dropdown portal mode
https://eightfoldai.atlassian.net/browse/ENG-30463
TBD
=> fix: a11y fixes in cases of portal dropdown

src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Panel/Panel.tsx, src/shared/FocusTrap/FocusTrap.tsx
fix: panel: fix panel animation while closing
=> fix: panel: fix panel animation while closing

src/components/Accordion/Accordion.tsx, src/components/Accordion/accordion.module.scss
fix: accordion: remove body top border on borderd false
=> fix: accordion: remove body top border on borderd false

src/components/Panel/panel.module.scss
Fixed panel overflow
https://eightfoldai.atlassian.net/browse/ENG-31916
skip
=> fix: overflow fix in the panel

src/components/Dropdown/Dropdown.tsx
=> fix: dropdown: remove force focus on portaled dropdown

src/components/Slider/Context.ts, src/components/Slider/Marks/Mark.tsx, src/components/Slider/Marks/index.tsx, src/components/Slider/Slider.stories.tsx, src/components/Slider/Slider.test.tsx, src/components/Slider/Slider.tsx, src/components/Slider/Slider.types.ts, src/components/Slider/Steps/Dot.tsx, src/components/Slider/Steps/index.tsx, src/components/Slider/Util.ts, src/components/Slider/slider.module.scss, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/octuple.ts
Adds the following:
- Thumb Tooltips
- Read only state
- Custom markers
- Dots option
- Ability to hide thumb
Also add ability to style tooltip, fixes slider show label.
https://user-images.githubusercontent.com/99700808/199807787-1a8f6c23-d695-44b2-a4b3-b77e125c72d0.mp4
ENG-33990
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Slider stories behave as expected.
=> feat: slider: add custom marker, dots, hide thumb, tooltip, read only support

src/components/Table/Internal/Body/Body.types.ts, src/components/Table/Internal/Body/BodyRow.tsx, src/components/Table/Internal/Body/index.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.tsx
feat: table: add on row hover event
=> feat: table: add on row hover event

src/components/Table/Internal/Body/Body.types.ts, src/components/Table/Internal/Body/BodyRow.tsx, src/components/Table/Internal/Body/index.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.tsx
Changed mouse event on table row hover to prevent event bubbling.
https://stackoverflow.com/a/34071888
=> fix: changed mouse event on table row hover

src/components/Pills/Pill.tsx, src/components/Pills/pills.module.scss, src/components/Upload/upload.module.scss
Fixes small regression caused by vartheme change
Pixel pushes image list view icon in `Upload` component so that it's centered.
N/A
=> fix: pill: fixes pill button hover and active styles to inherit from pill

src/octuple.ts
=> fix: export stats tab

src/octuple.ts
Updates exports to include `Carousel`, `Slide` and `TabSize`.
N/A
N/A
N/A
=> fix: carousel and tabs: exports carousel slide and tab size

CHANGELOG.md, package.json
=> chore(release): 2.20.3

src/components/Skeleton/skeleton.module.scss
fix: skeleton: use lighter colors in skeleton
=> fix: skeleton: use lighter colors in skeleton

src/components/Trigger/Styles/mask.scss, src/components/Trigger/trigger.module.scss, src/styles/base/_motion.scss
Fixes hide animations:
- Updates hide animation curve to `easein`.
- Adds 20% buffer to slide out animations to reduce jerkiness.
https://user-images.githubusercontent.com/99700808/210433244-5efbc391-eae0-4d7c-94a9-7ffb12858657.mp4
https://github.com/EightfoldAI/octuple/issues/464
ENG-38078
Pull the PR branch and run `yarn` and `yarn storybook`. Verify DatePicker animations no longer flicker on dismiss.
=> fix: picker: fixes trigger hide animation curves and updates slide out animations

src/components/Pagination/pagination.module.scss
1 line css change fixing a pixel shift regression ahead of release.
=> fix: pagination: updates border css property to outline, fixing pixel shift regression

src/components/Tabs/tabs.module.scss, src/components/Upload/Internal/uid.ts
Fixes rendering error caused by useMemo in an internal class component. 
Also fixes Pill tab badge default color regression.
=> fix: upload: fixes rendering error caused by hooks in class component uid utility regression

src/components/Slider/Slider.tsx
fix: slider: update state when value changes externally
https://eightfoldai.atlassian.net/browse/ENG-39478
=> fix: slider: update state when value changes externally

.github/workflows/octuple-publish-alerts.yml
=> chore: fix publish workflow

src/components/Button/button.module.scss
Ensures inner z indices are scoped to button only
=> chore: button: ensure inner z index are scoped to button only

.github/workflows/octuple-publish-alerts.yml
chore: fix publish alert workflow
=> chore: fix publish alert workflow

.github/workflows/octuple-publish-alerts.yml
Change to include all previous steps in Slack workflow.
=> chore: actions: including prerelease checkout and run steps in slack workflow

src/components/Menu/MenuItem/menuItem.module.scss
fix: menulinks: fix font weight
=> fix: menulinks: fix font weight

src/components/ConfigProvider/ConfigProvider.stories.tsx
Fixes a null ref error in Storybook.
=> fix: storybook: fixes null ref error on var theme

src/octuple.ts
=> chore: pagination: exports paginationvisiblepagercountsizeoptions

src/components/Accordion/accordion.module.scss, src/styles/themes/_default-theme.scss
Moves `Accordion` CSS Variables to global scope, adds a few more to improve theme support.
ENG-50965
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Accordion` stories behave as expected.
=> fix: accordion: custom theme support

src/components/CheckBox/checkbox.module.scss, src/components/RadioButton/radio.module.scss, src/styles/themes/_default-theme.scss
Adds semantic global variables to support var theme for `Check Box`, `Toggle Switch,` and `Radio Button` 
https://github.com/EightfoldAI/octuple/issues/648
ENG-57119
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `Check Box`, `Toggle Switch,` and `Radio Button` stories behave as expected.
=> feat: selectors: add var theme support to check box radio and toggle

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx
- Adds additional Story emulating Filters UI and its advanced visual state implementation
- Adds additional unit test emulating and validating Filters UI and its advanced visual state implementation
ENG-56197
ENG-56198
N/A
Pull the PR branch and run `yarn`, `yarn storybook`, and `yarn test:update` to verify the change.
=> chore: dropdown: adds advanced visibility story and unit tests

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.test.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, src/components/Atom/Atom.test.tsx, src/components/Atom/__snapshots__/Atom.test.tsx.snap, src/components/Badge/Badge.test.tsx, src/components/Badge/__snapshots__/Badge.test.tsx.snap, src/components/List/List.test.tsx, src/components/List/__snapshots__/List.test.tsx.snap, src/components/Loader/Loader.test.tsx, src/components/Loader/__snapshots__/Loader.test.tsx.snap, src/components/Navbar/Navbar.test.tsx, src/components/Navbar/__snapshots__/Navbar.test.tsx.snap, src/components/OcBase/OcBase.test.tsx, src/components/OcBase/__snapshots__/OcBase.test.tsx.snap, src/components/Portal/Portal.test.tsx, src/components/Skeleton/Skeleton.test.tsx, src/components/Skeleton/__snapshots__/Skeleton.test.tsx.snap, src/components/Spinner/Spinner.test.tsx, src/components/Spinner/__snapshots__/Spinner.test.tsx.snap, src/components/Stack/Stack.test.tsx, src/components/Stack/__snapshots__/Stack.test.tsx.snap
- Adds unit tests to components that lack coverage completely
- `Accordion`
- `Atom`
- `Badge`
- `List`
- `Loader`
- `Navbar`
- `OcBase`
- `Portal`
- `Skeleton`
- `Spinner`
- `Stack`
ENG-58940
Pull the PR branch and run `yarn` and `yarn test`.
=> chore: coverage: adds unit tests to components that need them

README.md, src/CONTRIBUTING.md
- Updates codecov url and text in README
- Updates text in CONTRIBUTING
N/A
N/A
N/A
N/A
=> chore: documentation: updates readme and contributing markdown files

SECURITY.md
Adds SECURITY.md
ENG-61902
N/A
N/A
N/A
=> chore: governance: add security policy

src/octuple.ts
Exports VisibilityContext to support custom next/previous `Carousel` button events.
N/A
N/A
N/A
N/A
=> chore: carousel: export visibilitycontext to support custom controls

src/components/InlineSvg/InlineSvg.tsx
handle undefined url scenarios
=> chore: inlinesvg: handle undefined url and previous url fallback to empty

src/components/Breadcrumb/Breadcrumb.test.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/Breadcrumb.types.tsx, src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Link/Link.tsx, src/components/Link/Link.types.ts, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/Navbar/__snapshots__/Navbar.test.tsx.snap
- Updates `Link` to make title `optional` via spread
ENG-73490
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Link` stories behave as expected.
=> chore: link: make title optional and inherit type from base

README.md, src/CONTRIBUTING.md, src/components/COMPONENTS.md
Updates some markdown content, removes a TBD.
N/A
N/A
N/A
=> chore: readme: updates markdown content

src/components/Upload/UploadList/index.tsx
Hides button when appropriate.
=> chore: upload: ensure remove icon button change is backward compatible

src/components/Inputs/TextInput/TextInput.tsx, src/components/List/List.tsx, src/components/Select/Select.stories.tsx
=> chore: sanity: pre release checklist sanity test fixups

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/tooltip.module.scss, src/components/Truncate/Truncate.test.tsx, src/components/Truncate/Truncate.tsx, src/components/Truncate/Truncate.types.ts, src/components/Truncate/index.ts, src/hooks/useTruncate.test.tsx, src/hooks/useTruncate.tsx, src/octuple.ts, src/shared/utilities/index.ts, src/shared/utilities/overflow.test.ts, src/shared/utilities/overflow.ts
- Adds `overflow` utilities `hasHorizontalOverflow`, `hasOverflow` and `hasVerticalOverflow`
- Adds `useTruncate` hook
- Adds `Truncate` component that broadcasts truncation boolean state by id
- Updates `Tooltip` stories to implement `Truncate` and demonstrate only enabling `Tooltip` when necessary
- Exports new features and utilities
https://github.com/EightfoldAI/octuple/assets/99700808/84375139-dc32-46cd-8036-ebc3495eef83
ENG-86929
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Tooltip` stories behave as expected.
=> feat: truncate: adds truncate hook and component with overflow utils

src/components/Progress/Progress.stories.tsx
Updates a story layout
N/A
N/A
N/A
=> chore: progress: update story

src/components/CheckBox/CheckBox.stories.tsx, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/CheckBoxGroup.tsx, src/components/CheckBox/Checkbox.types.ts, src/components/RadioButton/Radio.types.ts, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/RadioGroup.tsx
Add aria-describedby prop to radio and checkbox components
ENG-93791
=> fix: selectors: add aria attributes

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Select/select.module.scss
This reverts commit 7330c306247447a65e6400df5d0e1b9b4076d2d4.
We have deemed this change as introducing breaking changes. We will revisit some of the improvements and functional changes it introduces in the future
Nothing to test here. Direct revert.
=> chore: Revert "feat: select: performance optimizations and features

package.json, tsconfig.json, yarn.lock
1. Modifies the `tsconfig.json` to enable JSDoc comments to be compiled with the compiled `.d.ts` files. This is a DX improvement allowing developers to reference the types instead of needing to look at source code or documentation when writing components.
```ts
// lib/components/Dropdown/Dropdown.types.d.ts
// BEFORE: ❌ No JSDoc comments are emitted to the .d.ts files, with 
export interface DropdownProps {
ariaRef?: React.MutableRefObject<HTMLElement>;
children?: React.ReactNode;
// ...
}
// After:  ✅ JSDoc comments are emitted to the .d.ts files
export interface DropdownProps {
/**
* The ref of element that should implement the following props:
* 'aria-controls', 'aria-expanded', 'aria-haspopup', 'role'
* @default child
*/
ariaRef?: React.MutableRefObject<HTMLElement>;
/**
* The child …
```
=> feat: typescript improvements

src/components/Carousel/Tests/__snapshots__/Slide.test.tsx.snap, src/components/Pagination/Pager.tsx, src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, src/components/PersistentBar/__snapshots__/PersistentBar.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.expand.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.pagination.accepttrue.shot, src/components/Table/Tests/__snapshots__/Table.pagination.nocrashonchange.shot, src/components/Table/Tests/__snapshots__/Table.pagination.position.shot, src/components/Table/Tests/__snapshots__/Table.pagination.renders.shot, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap
Added aria label to pager according to guideline
Jira task - https://eightfoldai.atlassian.net/browse/ENG-102175
- pull branch down locally and start storybook (yarn storybook)
- with screen reader on, use tab key to interact with pages inside pagination list to observe it is announced as "page 1, page 2" and so on.
=> fix: pagination: Added aria label to pager according to guideline

src/components/Accordion/Accordion.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Fixes a typo in accordion role value
https://github.com/EightfoldAI/octuple/issues/880
look at the change
apply your brain
determine the fix is not insane
=> fix: accordion: typo in button role

package.json
Upgrading the octuple version in package.json
https://eightfoldai.atlassian.net/browse/ENG-116348
> This is bumping the version in the PR
=> feat: change version in package.json

src/components/Menu/Menu.stories.tsx, src/components/Menu/MenuItem/menuItem.module.scss
This removes the focus visible that was added as part of a PR in the octuple design language.
The PR in contention is #899 
https://eightfoldai.atlassian.net/browse/ENG-113537
> The existing test plan should take care of it. This is removing a CSS fix
=> feat: remove focus visible

CHANGELOG.md, package.json
Upgrading octuple library
https://eightfoldai.atlassian.net/browse/ENG-116348
> This is a new release
=> chore(release): 2.52.16

package.json
This will remove html tags during npm search
None
=> fix: description update

src/components/Table/Table.tsx
Reverts EightfoldAI/octuple#952
=> Revert "fix(table): update aria labels, add handleRowHover function"

src/components/Pills/Pill.tsx, src/components/Pills/__snapshots__/Pill.test.tsx.snap, src/components/Select/__snapshots__/Select.test.tsx.snap
Fixed the regression issue which was caused by [this change](https://github.com/EightfoldAI/octuple/pull/989/files). That change was done to fix failing npm test in vscode caused by https://github.com/EightfoldAI/octuple/pull/981/files
https://eightfoldai.atlassian.net/browse/ENG-144677
=> fix: regression issue fix

src/components/Tabs/Tab/Tab.tsx
Fixed Uncaught TypeError: Cannot read properties of undefined (reading 'match')
=> fix: tab issue causing frontend error
