EightfoldAI/octuple

README.md, package.json
the readme was using relative urls, this change fixes it
=> fix: readme: fixes asset and documentation urls

.npmignore, package.json, webpack.prod.js
Using components from the current release results in this error code https://reactjs.org/docs/error-decoder.html/?invariant=321
This change sets-up webpack to ignore adding react and react-dom to the prod bundle
=> fix: react: ignore react in production build to avoid conflicts

package.json
Auto installed dep needs to be a dev dependency
=> chore: install peers: moves install peers to dev dependencies

src/components/Button/BaseButton.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.types.ts, src/components/Button/DefaultButton/DefaultButton.tsx, src/components/Button/NeutralButton/NeutralButton.tsx, src/components/Button/SecondaryButton/SecondaryButton.tsx, src/components/Button/button.module.scss, src/components/Button/index.ts, src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.stories.tsx, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Inputs/TextArea/TextArea.stories.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.stories.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/hooks/useMatchMedia.ts, src/octuple.ts
fix: useMatchMedia set smallest width to 0
=> feat: button and input: adds neutral button, exports components, renames enum to better match others

src/components/Button/button.module.scss
in some scenarios the root style was overriding the local
=> fix: button: use root inverse text color instead of local variable

src/components/Selectors/RadioButton/RadioButton.tsx, src/components/Selectors/Selectors.types.ts
Update Selectors to inherit from OcBaseProps
-   [x] Tests for this change already exist
=> fix: extend RadioButtonProps and CheckBoxProps to OcBaseProps

src/components/Selectors/Selectors.types.ts
Remove classname prop from CheckBoxProps
-   [x] Tests for this change already exist
=> fix: remove classname prop from CheckBoxProps

src/components/Selectors/RadioButton/RadioGroup.context.tsx
Adds null check to onchange event. This was caught by running a jest update.
ENG-13963
=> fix: selectors: adds null check to radio button onchange event

src/components/Tabs/Tab/Tab.tsx
forward classNames to tab component
=> fix: forward classNames to tab component

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/tooltip.module.scss
allow pointer events when tooltip is disabled
=> fix: tooltip: allow pointer events when tooltip is disabled

.github/workflows/build.yml
Ci pipeline will run on prs created to main-next branch
=> chore: make ci builds run on main next

src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.tsx
Updates types and adds forward ref to input components.
ENG-13961
Ensure components may accept a ref from their HOC
=> fix: inputs: adds forward ref support, adjusts default wait interval

src/__snapshots__/storybook.test.js.snap, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/Pagination.types.ts
Previously, the page size and jumper didn't work because they only were set when the component rendered, this updates those to useEffect and update dynamically. Also adds a variable to track the total number of pages is greater than 1 to determine the visibility of certain elements that are only relevant when there are more than 1 page. Adds a wrpper to check if there are more than 0 pages, if not hide all elements.
ENG-13961
Test by setting to total to 0, 1 and 100 dynamically via a query.
=> fix: pagination: enables page size and jumper controls and hides elements via total

package.json, src/__snapshots__/storybook.test.js.snap, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/shared/utilities.test.tsx, src/shared/utilities.ts, yarn.lock
Previously Tooltips would render relative to their immediate parent element, potentially leading to clipping in some scenarios. This change adds a `ConditionalWrapper` utility `FC` and a `portal` prop to `Tooltip`. Enabling portaled Tooltips.
ENG-13961
add the portal prop to a Tooltip and ensure it renders as a portaled element
=> feat: tooltip: adds portal prop to tooltips

src/components/Pagination/Pagination.tsx
Pagination component didn't take latest changes of total hence not rendering at all even later on when total > 0
https://eightfoldai.atlassian.net/browse/ENG-22083
=> fix: add total in dependencies to pickup latest changes

src/components/Inputs/TextArea/TextArea.tsx
fix: textarea: event persist issue in react 16
https://eightfoldai.atlassian.net/browse/ENG-22443
=> fix: textarea: event persist issue in react 16

src/components/Button/button.module.scss, src/shared/variables.ts, src/styles/themes/_definitions-light.scss
The `:focus` selector property is not needed. It was reported that the buttons appeared to be stuck in an active state after click. This change removes `:focus` and defers to `.focus-visible:focus-visible`, only showing the focused state when using keyboard via the ConfigProvider.
ENG-22620
NA
Pull the PR changes, build storybook and verify focus styles and that they only appear when using keyboard in the ConfigProvider story view.
=> fix: button: removes focus outline and border style when not in keyboard mode

src/components/Tabs/tabs.module.scss
fix: tabs: allign first item to the left
https://eightfoldai.atlassian.net/browse/ENG-22845
=> fix: tabs: allign first item to the left

src/components/Table/Styles/bordered.scss, src/components/Table/Styles/table.module.scss, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.tsx
fix: table: increase selection column size, add border bottom header prop
https://eightfoldai.atlassian.net/browse/ENG-22952
=> fix: table: increase selection column size, add border bottom header prop

src/components/Button/BaseButton.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.types.ts, src/components/Button/DefaultButton/DefaultButton.tsx, src/components/Button/NeutralButton/NeutralButton.tsx, src/components/Button/PrimaryButton/PrimaryButton.tsx, src/components/Button/SecondaryButton/SecondaryButton.tsx, src/components/Button/button.module.scss
Adding floatingButtonProps in BaseButton to enable it floating in botton right corner
https://eightfoldai.atlassian.net/browse/ENG-22373
In story book there should be an option to make button floating
also try "round" shape and different size, should always work
=> feat: eng-22373: enable floating buttons

src/octuple.ts
Slider component not exported
1. Skip for release
=> fix: slider component not exported

package.json, src/__snapshots__/storybook.test.js.snap, src/components/Slider/Slider.test.tsx, src/components/Slider/Slider.tsx, src/components/Slider/Slider.types.ts
There were several setState calls in my layout logic which were triggering re-render. Eliminated these so that layout changes were done directly via ref updates. Also added ResizeObserver for triggering layout updates.
https://eightfoldai.atlassian.net/browse/ENG-23989
Added a unit test to ensure onChange doesn't fire on initial render.
=> fix: prevent slider from firing onChange during init

src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/components/Inputs/input.module.scss, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/select.module.scss
- adds select shapes and sizes mapped to input
- refines left and right icon layouts in input component
https://user-images.githubusercontent.com/99700808/179634323-e085f701-db88-4ae0-acdc-32cbcde635b7.mp4
ENG-22505
TODO: Add UTs for Select and Input
Pull latest and run `yarn` and `yarn storybook`. Verify the following:
Select:
shape
size
Icon should now be on the right and correctly reflect the chevron in Figma Theme 1.
=> fix: select: Move chevron indicator to the right side

src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/Select/select.module.scss, src/hooks/useMatchMedia.ts, src/styles/themes/_definitions-light.scss
implement addlistener fallback for older browsers and pixel push datepicker and select
see: https://www.designcise.com/web/tutorial/how-to-fix-the-javascript-typeerror-matchmedia-addeventlistener-is-not-a-function#:~:text=If%20you're%20getting%20the,which%20is%20returned%20by%20window.
Some older and specific browser versions don't support `window.matchMedia(e).addEventListener`, this change adds an `addListener` fallback to this hook.
ENG-24869
Pull the latest Octuple and `yarn` and then `yarn storybook` using node 16. Then verify the button component still resizes as expected in flex mode. If you're running MacOS version Version 12.1.2 …
=> fix: usematchmedia: implement addlistener fallback for older browsers

src/__snapshots__/storybook.test.js.snap, src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Dialog/BaseDialog/BaseDialog.types.ts, src/components/Dialog/BaseDialog/base-dialog.module.scss, src/components/Dialog/Dialog.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
Adds three additional optional action buttons to the header of Dialogs and Modal
https://user-images.githubusercontent.com/99700808/179872115-cd4ede54-754b-4abc-9e39-67077f45f8a1.mp4
ENG-22374
Pull the latest pr then run `yarn` and `yarn install`. Verify the following story:
Modal:
Header Actions
=> feat: modal: add three additional header action button props

webpack.common.js
chore: change class name hash for theme2.
Change in theme2 octuple class name hash generation. theme2 will have a slightly longer hash and classes should no overlap in theme1 and theme 2
=> chore: change class name hash for theme2

src/__snapshots__/storybook.test.js.snap, src/components/Inputs/TextInput/TextInput.tsx, src/components/Inputs/input.module.scss, src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts, src/components/Pills/pills.module.scss, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/select.module.scss
- Adds XSmall Pill size
- Fixes Select Pills so they truncate with an ellipses and look like Pills
- Adds close button to Select Pills so they may be edited on the fly
- Adds empty state text to Select Dropdown
- Centers Select Dropdown Spinner
- Fixes right icon Text Input padding when clear button isn't shown
https://user-images.githubusercontent.com/99700808/179865168-a573931b-5241-48cb-8265-cb49b16c0cb5.mp4
ENG-22497
ENG-22511
ENG-22510
ENG-22507
TODO: Add UTs for Select and Input components
Pull the latest and run `yarn` and `yarn install` then verify the following components:
Select
TextInput
=> fix: select: fixes pills, filtering, empty text, and spinner position

src/components/Dialog/BaseDialog/BaseDialog.tsx, src/components/Dialog/BaseDialog/BaseDialog.types.ts, src/components/Dialog/Dialog.tsx, src/components/Modal/Modal.tsx, src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Panel/Panel.types.ts, src/components/Panel/panel.module.scss, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.tsx, src/src/components/Panel/__snapshots__/Panel.stories.storyshot, src/src/components/RadioButton/__snapshots__/RadioButton.stories.storyshot
Fixes bug where there was a need to double click on radio buttons to update bespoke groups. Also adds header action buttons to panel and normalizes close button props
ENG-24745
Pull the pr branch and run `yarn`, then `yarn storybook` and verify the changes by testing the Bespoke Radio Group story.
=> fix: radiobutton: multiple radio buttons on the same page doesnt work as intended

src/components/Slider/Slider.tsx
Small change to fix component when host app uses react 16
ENG-25504
Pull changes, downgrade React peer deps to React 16.14.0 deps and test Slider story
=> fix: slider: fixes slider onresize event hang in react 16

src/components/Tooltip/Tooltip.tsx, src/src/components/Inputs/SearchBox/__snapshots__/SearchBox.stories.storyshot, src/src/components/Inputs/TextArea/__snapshots__/TextArea.stories.storyshot, src/src/components/Inputs/TextInput/__snapshots__/TextInput.stories.storyshot, src/src/components/Label/__snapshots__/Label.stories.storyshot, src/src/components/Table/__snapshots__/Table.stories.storyshot, src/src/components/Tooltip/__snapshots__/Tooltip.stories.storyshot
https://eightfoldai.atlassian.net/browse/ENG-24280
=> fix: tooltip: fixes tooltip visibility upon on mouse leave

src/components/Slider/Slider.stories.tsx, src/components/Slider/Slider.tsx, src/src/components/Slider/__snapshots__/Slider.stories.storyshot
Moves onChange callback into the handler, removes `useEffectOnlyOnUpdate` reference and adds some typings
ENG-25504
Pull changes, downgrade React peer deps to React 16.14.0 deps and test Slider story
peer deps change -->
```
"peerDependencies": {
"@types/react": "^16.9.49",
"@types/react-dom": "^16.9.8",
"react": "^16.14.0",
"react-app-polyfill": "3.0.0",
"react-dom": "^16.14.0"
},
```
=> fix: slider: fixes slider onchange event hang in react 16

src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/radio.module.scss, src/src/components/RadioButton/__snapshots__/RadioButton.stories.storyshot
When the RadioButton is used in a thinner layout, the first element gets distorted. This change ensures the width is consistent.
ENG-25650
Verify the additional stories by either pulling the pr and doing `yarn`, and `yarn storybook` or implement a radio group using the pr CodeSandbox React build, resize the browser to test the layout of the group.
=> fix: radiobutton: fixes width of radio element in flex when layout is constrained

src/components/RadioButton/RadioButton.stories.tsx, src/src/components/RadioButton/__snapshots__/RadioButton.stories.storyshot
The Storybook implementation was not scoping the Radio groups properly, this fixes the stories and the args to properly scope the groups and fix selections in both Canvas and Docs views, improving documentation.
ENG-25650
Pull the pr and do `yarn`, then `yarn storybook`, verify the changes in Radio stories. or use CodeSandbox CI and implement the groups to verify - using the story implementation as guidance.
=> fix: radio group: updates story implementation to scope selection states

src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx
fix: pagination: fix onCurrentChange event getting fired on change of total
https://eightfoldai.atlassian.net/browse/ENG-25039
=> fix: pagination: fix onCurrentChange event getting fired on change of total

src/components/Navbar/navbar.module.scss, src/styles/abstracts/_mixins.scss
The NavBar component may contain  non-octuple components. Need to scope resets here too.
ENG-26289
=> fix: navbar: apply scoped css resets to navbar component

src/components/Inputs/input.module.scss
This changes to make pill the default shape regressed the default rectangle shape in css. This change reverts the regression and updates the radius to map to theme 2.
ENG-26634
Pull the pr branch and run `yarn`, then `yarn storybook`, then verify the change in Input stories - or use CodeSandbox CI and implement a `TextInput` and `TextArea` with `shape={TextInputShape.Rectangle}`
=> fix: input: fixes rectangle shape for theme 2 input and textarea

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/select.module.scss, src/src/components/Select/__snapshots__/Select.stories.storyshot
Octuple Select w/ clear component ([link](https://eightfoldai.github.io/octuple.github.io/?path=/story/select--with-clear))
Steps to reproduce the bug:
Select School from the dropdown
You see the clear button (x) to the left of “School”
Select School again.
You don’t see the clear button
Select School again and you’ll see the clear button.
https://user-images.githubusercontent.com/99700808/184056277-b2f07ef3-76a4-4b47-87dc-984d3b36efb8.mp4
ENG-26684
Pull the pr changes and run `yarn`, then `yarn storybook`, verify changes to the Select With Clear story, or implement a clearable select via CodeSandbox CI
=> fix: select: fixes select clear when items are toggled

src/components/Button/button.module.scss, src/components/Link/link.module.scss, src/components/Menu/MenuItem/menuItem.module.scss, src/components/Table/Styles/table.module.scss, src/components/Tabs/tabs.module.scss
A recent update to remove some global resets to `<button>` elements regressed the `focus-visible` styles. This change fixes and applies the global style to all buttons in Octuple components
ENG-26733
pull the pr branch and run `yarn`, then `yarn install` and verify via the `ConfigProvider` story the styles via tabbing around the components (excluding the color pickers). Or implement a `button` in a `ConfigProvider` using CodeSandbox CI.
=> fix: button: use configprovider focus visible styles

src/components/CheckBox/checkbox.module.scss
Same as RadioButton and Checkbox, with longer labels or nodes, the selector gets squished.
ENG-26810
-   [ X] Bugfix Pull Request
=> fix: toggle: fix toggles getting squished in certain scenarios

src/components/Table/Styles/table.module.scss
fix: table: remove background from a sorted row
=> fix: table: remove background from a sorted row

src/components/Button/Button.stories.tsx, src/components/Button/Button.types.ts, src/components/Button/SystemUIButton/SystemUIButton.tsx, src/components/Button/button.module.scss, src/src/components/Button/__snapshots__/Button.stories.storyshot
Exposed prop to enable transparent background in SystemUI button
https://user-images.githubusercontent.com/109717425/185600355-1ff534fe-790c-4133-acb5-20e490e8a15c.mov
https://eightfoldai.atlassian.net/browse/ENG-27005
=> fix: added transparency prop to system ui button

src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Menu/Menu.tsx
feat: dropdown: add prop to disable closing on clicking outside
=> feat: dropdown: add prop to disable closing on clicking outside

src/components/Badge/Badge.tsx, src/components/Badge/badge.module.scss, src/src/components/Accordion/__snapshots__/Accordion.stories.storyshot, src/src/components/Badge/__snapshots__/Badge.stories.storyshot, src/src/components/Button/TwoStateButton/__snapshots__/TwoStateButton.stories.storyshot, src/src/components/Button/__snapshots__/Button.stories.storyshot, src/src/components/Tabs/__snapshots__/Tabs.stories.storyshot
=> fix: badge: fix font size

src/components/Select/Select.tsx, src/components/Select/select.module.scss
The redundant options change was triggering a second onClick event with no value, recent changes to the Dropdown component remove the need to do this.
https://user-images.githubusercontent.com/99700808/186051144-0810b0fc-8609-422f-8d7c-a55ac28ef6c9.mp4
ENG-27401
pull the pr changes and run `yarn`, then `yarn storybook`, verify the changes in the Select stories and this component behaves as expected.
=> fix: select: fixes pills layout and removes redundant options change

src/components/Pagination/Pagination.tsx
Added outside control for `_currentPage` in Pagination
This fix will be needed for https://github.com/EightfoldAI/octuple/pull/322 so that we can set the page back to 1 when certain action is triggered
https://eightfoldai.atlassian.net/jira/software/c/projects/ENG/boards/29?modal=detail&selectedIssue=ENG-26836
https://eightfoldai.atlassian.net/jira/software/c/projects/ENG/boards/29?modal=detail&selectedIssue=ENG-27400
-   [x] Tests for this change already exist
=> fix: update page as currentPage prop value updates

src/components/Button/BaseButton.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.types.ts, src/components/Button/button.module.scss, src/components/Loader/Loader.stories.tsx, src/components/Loader/Loader.tsx, src/components/Loader/Loader.types.ts, src/components/Loader/index.ts, src/components/Loader/loader.module.scss, src/components/Select/Select.stories.tsx, src/components/Tabs/Tab/Tab.tsx, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.types.ts, src/components/Tabs/tabs.module.scss, src/octuple.ts, src/src/components/Tabs/__snapshots__/Tabs.stories.storyshot, src/styles/base/_motion.scss
feat: add loading state in button and tabs
=> feat: add loading state in button and tabs

src/components/Menu/MenuItem/menuItem.module.scss
fix: menuitem: add no wrap do long text doesnt wrap to next line
skip
=> fix: menuitem: add no wrap so long text doesnt wrap to next line

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/src/components/Select/__snapshots__/Select.stories.storyshot
The Tooltip portal property renders the tooltip below surface UI when surface UI is the parent. Reverting this change and use position prop instead.
ENG-28213
pull the PR branch then do `yarn` and `yarn storybook` to verify the tooltip position and it still shows for the typical use case.
=> fix: select: removes portal property from tooltip and replace with position

src/components/Inputs/SearchBox/SearchBox.tsx
fix: searchbox: set default shape to pill
=> fix: searchbox: set default shape to pill

src/components/RadioButton/radio.module.scss
fix: radio button size.
The [PR](https://github.com/EightfoldAI/octuple/pull/332) changed the radio selector label size. This impacted Radio's across TA & starts to break the UI at multiple places. Reverting the changes in this PR.
1. skip
=> fix: radio button size

src/components/CheckBox/checkbox.module.scss
fix: check box sizes
The https://github.com/EightfoldAI/octuple/pull/332 changed the checkbox selector label size. This impacted Checkboxes across TA & starts to break the UI at multiple places. Reverting the changes in this PR.
1. Skip
=> fix: check box sizes

src/components/Table/Internal/octable.module.scss
fix: table: clip long table header text
=> fix: table: clip long table header text

src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.types.tsx
The Octuple Table was missing its type annotations. Also needed to omit a private transfomColumns property
ENG-29039
N/A
Run `yarn` and `yarn storybook`. Verify the Table stories behave as expected.
=> fix: table: adds type annotations and omits private transformColumns property

src/components/Label/Label.stories.tsx, src/components/Label/Label.test.tsx, src/components/Label/Label.tsx, src/components/Label/Label.types.ts, src/components/Label/label.module.scss, src/src/components/Dialog/__snapshots__/Dialog.stories.storyshot, src/src/components/Inputs/SearchBox/__snapshots__/SearchBox.stories.storyshot, src/src/components/Inputs/TextArea/__snapshots__/TextArea.stories.storyshot, src/src/components/Inputs/TextInput/__snapshots__/TextInput.stories.storyshot, src/src/components/Label/__snapshots__/Label.stories.storyshot, src/src/components/Skeleton/__snapshots__/Skeleton.stories.storyshot
The info button of the Label was rather brittle, this improves it a bit and add support for custom buttons.
https://user-images.githubusercontent.com/99700808/189709781-dc9ce155-c3ce-4a0f-bded-dc768c76f96e.mp4
ENG-29160
Pull the pr branch and do `yarn` and `yarn storybook`. Verify the Label stories behave as expected
=> feat: label: add support for custom buttons and type clean up

src/components/Button/Button.stories.tsx, src/components/Button/button.module.scss, src/src/components/Button/__snapshots__/Button.stories.storyshot, src/src/components/Icon/__snapshots__/Icon.stories.storyshot
The floating, fixed round icon button not having a width caused distortion in some versions of Safari. This change adds a set width and height to floating buttons.
ENG-29154
-   [X] I have added snapshot tests for this change
pull the pr branch and do `yarn`, then `yarn storybook`. Verify the floating button story behaves as expected.
=> fix: button: fixes floating icon button distortion in some versions of safari

src/components/Link/link.module.scss
fix: remove flex style from link
=> fix: remove flex style from link

src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.types.ts, src/components/Tabs/Tabs/AnimatedTabs.tsx, src/components/Tabs/tabs.module.scss, src/styles/themes/_default-theme.scss
Many mocks include an edge-to-edge underline beneath tabs. Adding opt-in support for that line.
https://user-images.githubusercontent.com/106610186/193306451-564d6096-2392-447e-a235-70fd40d8ec7b.mov
NA
NA
-   [x] I have not added unittests for this change
Open any Tabs story (other than pill variant) and enable "underlined" control. Observe the presence of an underline
=> feat(tabs): add underlined option to tabs

src/components/Form/Tests/index.test.js, src/components/Inputs/Input.types.ts, src/components/Inputs/TextInput/TextInput.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
Previously the `Select` was not aware its `options` have changed, adds `_options` to existing `useEffect`
also adds a `boolean` to programmatically `clear` TextInput if `needed`.
https://user-images.githubusercontent.com/99700808/193370706-0901a4f3-8eaa-4129-81bc-a7a6b6212738.mp4
ENG-31020
Pull the pr branch and do `yarn`, then `yarn storybook`, verify the `Select` and `TextInput` stories behave as expected.
=> fix: select: update when options change

src/components/DateTimePicker/DatePicker/DatePicker.stories.tsx, src/components/DateTimePicker/DatePicker/Generate/generateRangePicker.tsx, src/components/DateTimePicker/DatePicker/Generate/generateSinglePicker.tsx, src/components/DateTimePicker/DatePicker/Styles/partial.scss, src/components/DateTimePicker/Internal/OcPickerPartial.tsx, src/components/DateTimePicker/Internal/OcPickerTrigger.tsx, src/components/DateTimePicker/Internal/OcRangePicker.tsx, src/components/DateTimePicker/Internal/Partials/DatePartial/DateHeader.tsx, src/components/DateTimePicker/Internal/Partials/Header.tsx, src/components/DateTimePicker/Internal/Partials/MonthPartial/MonthHeader.tsx, src/components/DateTimePicker/Internal/Partials/QuarterPartial/QuarterHeader.tsx, src/components/DateTimePicker/Internal/Partials/YearPartial/YearHeader.tsx, src/components/DateTimePicker/Internal/Tests/__snapshots__/partial.rtl.shot, src/components/DateTimePicker/Internal/Tests/__snapshots__/range.test.tsx.snap, src/components/DateTimePicker/Internal/Tests/range.test.tsx, src/components/DateTimePicker/Internal/Utils/getRanges.tsx, src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/Trigger/Popup/PopupInner.tsx, src/components/Trigger/Utils/alignUtil.ts, src/components/Trigger/trigger.module.scss, src/styles/base/_motion.scss, src/styles/themes/_default-theme.scss, src/styles/themes/_definitions.scss
Prior to this change the pickers used a visually hidden approach via `opacity`, this was problematic because the resize event would cause a noticeable flicker. This change updates the pickers to use `display: hidden`.
https://user-images.githubusercontent.com/99700808/193958529-d4992bbb-7430-4d75-99bd-824edea8675f.mp4
ENG-29871
Pull the pr branch and run `yarn` and `yarn storybook` via terminal. Verify the Pickers behave as expected.
=> fix: picker: fix flicker on resize, update buttons, and font weight to match latest design

src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Select/Select.tsx
Fixing flip behavior for filterable Select. 
When dropdown is opened upwards, the filtered dropdown would condense upwards instead of downwards. Example:
With this fix, the filtered dropdown will condense in the correct direction. 
NA
https://eightfoldai.atlassian.net/browse/ENG-31392
https://eightfoldai.atlassian.net/browse/ENG-31991 (clone)
WIP
=> fix(dropdown): modify flip behavior for filterable Select

src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
Missing button type caused form submit action, this change fixes the bug.
=> fix: select: adds html type to chevron button

src/octuple.ts
=> fix: exports: adds progress size and avatar group to exports

src/components/Pagination/Pager.tsx, src/components/Pagination/Pagination.tsx, src/components/Table/Tests/__snapshots__/Table.expand.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.pagination.accepttrue.shot, src/components/Table/Tests/__snapshots__/Table.pagination.nocrashonchange.shot, src/components/Table/Tests/__snapshots__/Table.pagination.position.shot, src/components/Table/Tests/__snapshots__/Table.pagination.renders.shot, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap
Updates `Pagination` to use the correct aria attributes to announce current page.
ENG-34426
Pull the PR branch and run `yarn`, and `yarn storybook`. Verify `Pagination` stories behave as expected. Turn on VoiceOver via System Preferences. Pagination should now appropriately announce the current item.
=> fix: pagination: fixes pagination aria attributes

yarn.lock
Upgrades packages that contain vulnerabilities (storybook and css module related developer deps)
Targeted fixes in yarn.lock to the following deps containing vulnerabilities detected by Dependabot:
- loader-utils (bumps all to at least v1.4.2, removes unused references)
- trim-newlines (removed unused reference)
ENG-35136
Pull the PR branch and run `yarn` and `yarn storybook`. Verify all stories behave as expected.
=> fix: security: dependabot audit deps fixup and upgrade vulnerable packages part two

src/components/Table/Hooks/useSelection.tsx, src/components/Table/Tests/__snapshots__/Table.fixselectionexpandonleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionwithcols.shot, src/components/Table/Tests/__snapshots__/Table.usecolselectionwithkey.shot
Previously, all selectors shared the same id, this change uses the row id to make them more unique to each row, preventing inadvertent select all.
- also removes an unused variable, adds some typings
https://github.com/EightfoldAI/octuple/issues/434
ENG-35001
-   [X] Tests for this change already exist (updated snaps)
pull the pr branch and run `yarn` and `yarn storybook`. Verify the `Table` `Selection` story behaves as expected.
=> fix: table: updates use selection hook selectors to have ids by row key

src/components/Table/Internal/Body/Body.types.ts, src/components/Table/Internal/Body/BodyRow.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.types.tsx
Added `rowKey` param on `onRowHover` callback
=> fix: added row key

src/components/Inputs/input.module.scss
Search expandable thumb position fix
https://eightfoldai.atlassian.net/browse/ENG-36644
N/A
=> fix: added position left on expandable search

src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.stories.tsx, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Inputs/TextInput/TextInput.stories.tsx, src/components/Inputs/TextInput/TextInput.tsx
Add missing support for autocomplete attribute so we can disable this in search circumstances where the autocomplete interferes with custom autocomplete implementations
In Storybook, inspect element in devtools to confirm there is no autocomplete attribute on the element. Add a value "off" and observe that the attribute and value are added to the Input as expected
=> feat: add support for autocomplete attribute to TextInput and SearchBox

.git-blame-ignore-revs, src/CONTRIBUTING.md
Squash and commit changed the commit hash referenced on previous 2 space indent. Also removing added line from CONTRIBUTING.md as the command update .git/config
No functional library changes
=> fix: update git-blame-ignore-revs to correct commit hash

.git-blame-ignore-revs, src/CONTRIBUTING.md, src/components/Card/card.module.scss, src/components/Table/Styles/table.module.scss, src/components/Tabs/tabs.module.scss, src/styles/abstracts/_mixins.scss, src/styles/themes/_default-theme.scss, src/styles/themes/_definitions.scss
When turning off border for StatTabs, remove the padding as designers will most often want the tabs flush with the surrounding content.
Additional enhancements to varTheme support.
Visual inspection of StatTabs to ensure they render as desired.
=> fix: remove padding from borderless stat-tabs, extend varTheme

src/components/Dropdown/Dropdown.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/shared/utilities/uniqueId.ts
This fixes a new unique Id being generated on every render
Before: 
https://user-images.githubusercontent.com/95337653/208393928-9ebc0fa3-6a86-409e-8c66-c7ad8ae7fe8f.mov
After:
https://user-images.githubusercontent.com/95337653/208394228-66dd376d-efd6-4a07-9c61-f9afd8318d89.mov
=> fix: only generate a unique id once

src/components/Accordion/accordion.module.scss, src/components/Button/button.module.scss, src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/Inputs/input.module.scss, src/components/Link/link.module.scss, src/components/Table/Styles/table.module.scss, src/components/Tabs/tabs.module.scss, src/components/Upload/upload.module.scss, src/styles/themes/_default-theme.scss, src/styles/themes/_definitions.scss
Makes the standard octuple focus styling varTheme friendly.
NA
NA
1. Checkout PR locally
2. Startup storybook
3.  Visual inspect focus styling on inputs and buttons to confirm they still work as expected
=> feat: make focus highlighting varTheme friendly

src/components/Button/button.module.scss
fix: twoStateButton: vertical align counter
=> fix: twoStateButton: vertical align counter

src/components/Inputs/input.module.scss
Fix for overlay in expandable search
=> fix: input: expandable search overlay zindex

src/components/Stack/Stack.stories.tsx, src/components/Stack/Stack.tsx, src/components/Stack/Stack.types.ts, src/components/Stack/stack.module.scss
feat: stack: use flex gap instead of margins
=> feat: stack: use flex gap instead of margins

src/components/Label/Label.stories.tsx, src/components/Label/Label.tsx, src/components/Label/Label.types.ts, src/components/Label/label.module.scss
Exposes all tooltip props via `labelIconButtonProps.tooltipprops`, marks others as deprecated in `labelIconButtonProps`.
https://github.com/EightfoldAI/octuple/issues/473
ENG-39123
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Label` stories behave as expected.
=> fix: label: exposes all tooltip props and fixes hover pixel shift

src/components/Tabs/Stat/Stat.tsx, src/components/Tabs/StatTabs.stories.tsx, src/components/Tabs/Tabs.types.ts, src/components/Tabs/tabs.module.scss, src/octuple.ts, src/styles/themes/_default-theme.scss
Enables validation status theming for individual stats, e.g. `error`, `success`, `warning`.
Fixes css variable typo that caused `Stat` borders not to render.
https://user-images.githubusercontent.com/99700808/210459828-b0698bee-7731-4408-bf23-572f291c94f9.mp4
ENG-34522
Pull the PR branch, run `yarn` and `yarn storybook`. Verify `Stat Tabs` stories behave as expected.
[ENG-34522]: https://eightfoldai.atlassian.net/browse/ENG-34522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: stat tabs: enable stat themes by validation status

src/components/Carousel/carousel.module.scss
limit carousel auto scroll to x axis, potential fix for the below issue.
https://github.com/EightfoldAI/octuple/issues/466
CSS only
Pull the pr branch and run `yarn` and `yarn storybook`. Verify the `Carousel` stories behave as expected.
=> fix: carousel: limit auto scroll to x axis only

src/hooks/useMaxVisibleSections.ts
fix: watch extra item width, padding and line to show for useMaxVisibleSections hook
=> fix: watch extra item width, padding and line to show for useMaxVisibleSections hook

src/components/Avatar/Avatar.types.ts, src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/ConfigProvider/Theming/Theming.types.ts, src/components/ConfigProvider/Theming/styleGenerator.ts, src/components/ConfigProvider/Theming/themes.ts, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts, src/components/Tabs/Stat/Stat.tsx, src/components/Tabs/StatTabs.stories.tsx, src/components/Tabs/Tabs.types.ts, src/octuple.ts
See issue for summary
Also rename and export StatThemeName
https://github.com/EightfoldAI/octuple/issues/493
ENG-39328
Pull the ps branch and run `yarn` and `yarn storybook`. Verify the `ConfigProvider` story behaves as expected.
=> fix: configprovider: export OcThemeNames from a better location, rename to OcThemeName

src/components/Carousel/Carousel.tsx, src/components/Carousel/ScrollMenu/ScrollMenu.tsx
Ensures next/prev buttons are visible only after scroll menu initialization completes and when the first or last items are not visible, respective to the appropriate button.
https://github.com/EightfoldAI/octuple/issues/466
ENG-39329
Pull the PR branch and run `yarn` and `yarn storybook` or use Codesandbox CI and implement `Carousel`. Verify the `Carousel` `Scroller` story behaves as expected with 24 items and 1 item.
=> fix: carousel: arrow blinks when its edge meets window edge

src/components/CheckBox/CheckBox.test.tsx, src/components/CheckBox/CheckBoxGroup.tsx
- Compares for `value` in `CheckBoxGroup` `onChange`
- Adds some typing
ENG-39406
- [] Tests for this change already exist
Pull the pr branch and run `yarn` and `yarn storybook`. Verify the `CheckBoxGroup` story behaves as expected.
=> fix: selectors: adds null value check to checkbox group onchange

src/components/DateTimePicker/DatePicker/datepicker.module.scss, src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/Inputs/input.module.scss, src/styles/themes/_default-theme.scss
Improves CSS Variables by adding more semantically named input border vars
Improves color-contrast ratio of input borders to greater than 4:5:1 for every state
https://github.com/EightfoldAI/octuple/issues/498
ENG-39677
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `Input`, `Date Picker` and `Time Picker` stories behave as expected.
=> fix: inputs: border color used for inputs is not a11y friendly

src/components/InfoBar/InfoBar.tsx
Updates the `InfoBar` close icon button to be round
ENG-39767
Pull the pr branch and run `yarn` and `yarn storybook`. Verify the `InfoBar` stories behave as expected.
=> fix: infobar: close icon button should be round

src/components/Table/Internal/Body/Scroller.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Internal/octable.module.scss, src/components/Table/Locale/en_GB.tsx, src/components/Table/Locale/en_US.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Table.types.tsx
feat: scroller for horizontally scrollable table
https://user-images.githubusercontent.com/95337653/213238699-e3fc7244-05d4-4a69-b1e5-7facfef9ff32.mov
https://eightfoldai.atlassian.net/browse/ENG-39334
=> feat: scroller for horizontally scrollable table

src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Updates condition to disable the next button
Adds unit tests to validate the scenario, along with a few others. 
ENG-41053
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Pagination` stories behave as expected.
=> fix: pagination: disable next button only when current page is equal to total page count

src/components/Pills/Pill.test.tsx, src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts, src/components/Pills/__snapshots__/Pill.test.tsx.snap, src/components/Pills/pills.module.scss, src/octuple.ts
- Adds `PillThemeName` and updates props to accept a union of `OCThemeName` or `PillThemeName`
- Allow custom close icon by moving the default prop before the spread
- Adds white theme support
- Updates storybook to include the custom close icon scenario
ENG-41058
ENG-39144
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Pill` stories behave as expected.
=> feat: pill: enable white theme and custom close icon

src/components/Dropdown/dropdown.module.scss
CSS change to ensure dropdown menu stays within the viewport
ENG-39856
Ensure https://eightfoldai.github.io/octuple.github.io/?path=/story/dropdown--dropdown-button continues to work as expected.
=> fix: dropdown now stays within the viewport

src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts, src/components/Pills/pills.module.scss
Add ellipse functionality to pill text
ENG-39494
Pull the PR branch and run yarn and yarn storybook. Verify the Pill stories behave as expected.
=> feat: pill text ellipse

src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx
When `lineClamp` is `null` or `0`, this causes a JSX exception. Update the expression to pass a null value to handle JSX. Updates storybook to include this test via default props. 
ENG-41517
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Pill` stories behave as expected after a hard reload and a `lineClamp` value of `0`.
=> fix: pill: handle jsx when lineclamp is null or zero

src/components/InfoBar/InfoBar.tsx
The default aria `role` of `InfoBar` was `presentation`, this change updates the default `role` to `alert` to improve interaction with screen readers. 
https://github.com/EightfoldAI/octuple/issues/503
ENG-41361
N/A
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `InfoBar` stories behave as expected.
=> fix: infobar: updates the default role prop value to alert

src/components/Button/Button.test.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/Button/button.module.scss
Adds missing zIndex selector property.
Adds unit test and snap validation.
https://user-images.githubusercontent.com/99700808/216103883-22ba37cb-91e2-4cdf-957a-9c2c9de2de20.mp4
ENG-42127
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Button` loader.
=> fix: button: update button loader z index to map to updated layout with nudge option

.github/workflows/octuple-publish-alerts.yml
Previous change was failing because the job depends on build and the first job may not contain deps
N/A
Should verify on next release
=> chore: actions: adds build job to octuple publish alerts

src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/ConfigProvider/ConfigProvider.types.ts, src/components/ConfigProvider/Theming/Theming.types.ts, src/components/ConfigProvider/Theming/themes.ts
ConfigProvider is currently providing default values unnecessarily. This makes it necessary to provide empty objects in config in order to avoid the undesired default values.
In this example, I'm trying to emulate a starbucks green theme, and if I don't provide an empty navbarTheme and tabsTheme then the defaults get copied in and I end up with blue tabs despite my varTheme.
Pull down the PR and run storybook locally. Select a new primary and/or accent color in ConfigProvider story. With this change, the tabs get updated appropriately. Current undesirable behavior is that they stay blue based on the default values.
=> fix: do not provide default colors for ConfigProvider

src/components/Menu/Menu.stories.tsx, src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx, src/components/Menu/MenuItem/menuItem.module.scss
feat: add secondary button in menu item
=> feat: add secondary button in menu item

src/components/Link/link.module.scss
`display: inline-block` was causing layout issues in vscode app Navbar implementation. This change isolates the display type to explicitly defined variants only, fixing the focus-visible borders in the app for already existing primary button variants. Also removes the need for link variants to require hard-coded widths.
=> fix: link: isolate css display inline block to variants other than default

src/components/Carousel/Carousel.stories.tsx, src/components/Carousel/Carousel.tsx, src/components/Carousel/Carousel.types.ts, src/components/Carousel/ItemsMap.ts, src/components/Carousel/Tests/ItemsMap.test.ts, src/components/Carousel/Tests/ScrollMenu.test.tsx, src/components/Carousel/Tests/Utilities.test.tsx, src/components/Carousel/Tests/autoScrollApi.test.ts, src/components/Carousel/Tests/useItemsChanged.test.tsx, src/components/Carousel/Utilities/index.ts, src/components/Carousel/Utilities/scrollBySingleItem.tsx, src/components/Carousel/autoScrollApi.ts
- Adds `single` prop to `Carousel`
- Handle mouse wheel scroll when it's over the carousel, so that scrolling the view vertically is prevented
- Adds `scrollBySingleItem` utility to take advantage of the `scrollBy` api to account for various occlusion offsets needed because the paddles overlap the content of the scrollable list
- Updates API methods to isolate group scroll
- Updates UTs
https://user-images.githubusercontent.com/99700808/217393035-bd24777b-d550-49ec-a972-68b76ebd7485.mp4
ENG-42767
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Carousel` stories behave as expected.
=> feat: carousel: add single prop and update api to support single item scroll

src/components/Skeleton/skeleton.module.scss
Curved elements' wave animation was not being cropped in Safari browser, this change fixes the overflow behavior.
Before (Safari):
https://user-images.githubusercontent.com/99700808/220462514-06d4dd3e-5de8-4d92-a365-f4194688c40c.mp4
After (Safari):
https://user-images.githubusercontent.com/99700808/220462562-5555149e-ab8d-4aa5-ba3c-6ed089322a87.mp4
ENG-44138
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Skeleton` stories behave as expected using Safari browser.
=> fix: skeleton: ensure wave overflow is hidden in safari browser

src/components/Button/button.module.scss
Using a CSS variable inside of a nested `calc` function isn't valid SASS, this change removes these property overrides to fix the `Size` nudge animation, because border is appended to the client rect, these overrides are unnecessary.
https://user-images.githubusercontent.com/99700808/220772475-8745647d-5bb4-4e11-80e0-0a5c44deb2df.mp4
ENG-44290
N/A CSS only
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `PrimaryButton` story behaves as expected when given the following `nudgeProps`:
```
{
"animation": "size",
"delay": 5000,
"enabled": true,
"iterations": 5
}
```
=> fix: nudge: removes unnecessary border calculations in css

src/components/Form/Tests/index.test.js, src/components/Popup/Popup.stories.tsx, src/components/Popup/Popup.test.tsx, src/components/Popup/Popup.tsx, src/components/Popup/Popup.types.ts, src/components/Popup/index.ts, src/components/Popup/popup.module.scss, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/components/Tooltip/tooltip.module.scss, src/octuple.ts
Adds `Popup` component, derived from `Tooltip`
Updates `Tooltip` component to enable `Popup` `type` using existing patterns via `floating-ui` dependency
Preserves `Tooltip` existing implementation to minimize risk via `getDefault` and `getPopup` functions
Adds `Popup` story
Adds and updates unit tests
https://user-images.githubusercontent.com/99700808/220430583-b6bd8acd-2961-4015-a770-c08a3e102d10.mp4
ENG-2819
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Tooltip and Popup stories behave as expected.
=> feat: popup: adds popup component

src/components/InfoBar/InfoBar.test.tsx, src/components/InfoBar/InfoBar.tsx, src/components/InfoBar/__snapshots__/InfoBar.test.tsx.snap, src/components/InfoBar/infoBar.module.scss, src/styles/themes/_default-theme.scss
- Adds `transparent` prop to `InfoBar` `SystemUIButton`
- Updates scss to include `InfoBar` `:hover` and `:active` `SystemUIButton` background colors
- Adds 7 unit tests
https://user-images.githubusercontent.com/99700808/220788433-3f13e674-d163-4f4c-9b42-8a5273d9f2ad.mp4
ENG-29876
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `InfoBar` stories behave as expected.
=> fix: infobar: buttons should have transparent background and inherit color

src/components/Icon/Icon.test.tsx, src/components/Icon/__snapshots__/Icon.test.tsx.snap
Adds `Icon` unit tests.
N/A
N/A
=> chore: icon: adds unit tests

.github/workflows/octuple-publish-alerts.yml
Ensure the proper node version is used by octuple-publish-alerts action.
=> chore: actions: update node env for publish alerts

src/components/Popup/Popup.stories.tsx, src/components/Tooltip/Tooltip.tsx
Initial Popup change omitted this condition, also ensures image flicker does not happen in Popup story
=> fix: popup: do not toggle when no content or disabled

.github/workflows/octuple-publish-alerts.yml
To get the current tag on the `workflow_run` instead of `push`, this change uses the `github.event.workflow_run.head_commit.tag` context in the `octuple-publish-alerts` workflow.
=> chore: actions: update how the tag version is defined using workflow run

src/components/Table/Internal/Body/Scroller.tsx, src/components/Table/Internal/FrameWrapper/FrameWrapper.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Table.stories.tsx
feat: table: show scroller on table rows
=> feat: table: show scroller on table rows

src/components/Avatar/Avatar.stories.tsx, src/components/Avatar/Avatar.tsx, src/components/Avatar/Avatar.types.ts, src/components/Avatar/AvatarGroup.stories.tsx, src/components/Avatar/AvatarGroup.tsx, src/components/Avatar/Styles/group.scss, src/components/Avatar/Styles/rtl.scss, src/components/Avatar/avatar.module.scss, src/styles/themes/_default-theme.scss
- Add `Avatar` status item **text** and **tooltip** support (this is needed because we required `Avatar+Tooltip` support in `AvatarGroup` but it was not working because of use of `cloneElement` in `AvatarGroup`)
- Improve `Avatar` status item placement CSS
- Fix undesired `Avatar` status item displacement in `AvatarGroup` due to border
- Fix `Avatar` outline when `src` is passed and `type === 'round'`
ENG-40399
Pull the PR branch and run yarn and yarn storybook. Verify the Avatar Group stories behave as expected.
Avatar status item text
Avatar tooltip
Avatar status item displacement in AvatarGroup - **before** and **after** the fix
`Avatar` outline when `src` is passed and `type === 'round'` - **before** and **after** the fix
=> Avatar status item text and tooltip support

src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Dropdown/dropdown.module.scss, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.test.tsx, src/components/Menu/Menu.tsx, src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx, src/components/Menu/MenuItem/MenuItemCustom/MenuItemCustom.tsx, src/components/Menu/MenuItem/MenuItemLink/MenuItemLink.tsx, src/components/Menu/MenuItem/MenuItemSubHeader/MenuItemSubHeader.tsx, src/components/Menu/MenuItem/menuItem.module.scss, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/Select/Select.stories.tsx, src/octuple.ts
This is a part of ENG-45561
- Adds `alignIcon` prop in preparation for recursive dropdown menu support
- maps `IconSize` to `MenuSize`, omits size from `IconProps` via `MenuIconProps`
- Adds getIcon method to `MenuItemButton` and `MenuItemLink`
- Ensure `disabled` from props is read by `MenuItemLink`
- Adds `wrap` prop to `MenuItem` and RTL styles to enable menu item text wrapping
- Ensures `menuitem` `<li>` content is focusable and take the full width and height possible for greater click target
- Maps `MenuSize` and `IconSize` before the `iconProps` spread to ensure default size is the same as `Menu`
- Fixes `<li>` rendering bug
- Alphabetizes props
- Reduces the size of the `Dropdown` border radius by `4px` to better match systems design Figma
- Fixes `Dropdown` drift into position bug …
=> feat: menuitem: adds align icon prop and fixes list item rendering bug

src/components/Carousel/Carousel.tsx, src/components/Carousel/Settings.ts, src/components/Carousel/Tests/ScrollMenu.test.tsx
- Simplifies the scroll behavior of `Carousel` `scroll` mode by deferring touchpad scroll behavior to the browser, ensuring consistency
- Only prevent default when using vertical mouse wheel event triggered by a proper mouse
ENG-46812
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Carousel` stories behave as expected.
=> fix: carousel: only handle wheel event when not using touchpad

src/components/Table/Internal/Body/Scroller.tsx
No scolling buttons when table body does not have a scrollbar 
When table is scrollable
When table is not scrollable
=> fix: no scolling buttons

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts
- Adds `object` prop to `SelectOption`
- Updates `onOptionsChange` callback to return `values` `string` array and its `options` `object` array
- Updates unit tests to account for the newly added `options` argument returned by the `onOptionsChange` callback
https://github.com/EightfoldAI/octuple/issues/562
ENG-46082
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Select` stories behave as expected.
=> fix: select: options change not reacting properly when value is an object

src/components/Tooltip/Tooltip.tsx
- Fixes rounding error by rounding down to nearest number, previously  the calculated `left`, `top` `style` positions that were floats would be auto-corrected by the browser resulting in a noticeable 1 pixel shift at run time.
- Fixes class prop typo of cloned `Tooltip` element.
ENG-46933
Before fix:
https://user-images.githubusercontent.com/99700808/226689782-8e5132d6-4b11-4e85-9258-70f97f88e322.mp4
After fix:
https://user-images.githubusercontent.com/99700808/226689860-c2929d8c-4874-4802-9bfc-83ec32960fb5.mp4
Pull the PR branch, run `yarn` and `yarn storybook`. Verify the `Tooltip` behaves as expected in the `Avatar` story suite.
=> fix: tooltip: fixes pixel position rounding error

src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Popup/Popup.tsx, src/components/Popup/Popup.types.ts, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts
Handle event propagation, disabled state and provide callbacks in `clonedElement` events.
N/A
Pull the PR branch and run `yarn`, `yarn storybook`. Verify `Dropdown`, `Tooltip`, `Popup`, `Menu`, and `Select` components behave as expected.
=> fix: dropdown: handle event propagation and disabled

src/components/Slider/Slider.stories.tsx, src/components/Slider/Slider.tsx, src/components/Slider/slider.module.scss
- Rounds down calculated pixels
- Replaces inaccurate `calc()` offset in CSS with `px` variables by `Slider` `size` of non-inline extremity labels
https://user-images.githubusercontent.com/99700808/228373726-792b8286-e15a-4f8f-9009-38a4fdaeb914.mp4
ENG-47094
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Slider` stories behave as expected.
=> fix: slider: pixel push extremity labels to better match thumb label position

src/components/Atom/Atom.types.ts, src/components/Button/Button.test.tsx
- Mark `data-test-id` as deprecated in favor of `data-testid` to better map to testing library deps
- Fixes flaky button animation UTs by removing sleep
Pull the PR branch and run `yarn` and `yarn test`.
=> chore: test: deprecate prop and fix flaky button unit tests

src/components/Popup/Popup.stories.tsx, src/components/Tooltip/tooltip.module.scss
Ensures CSS pseudo selector doesn't block cursor when over Popup
https://user-images.githubusercontent.com/99700808/230682142-54431dca-118e-4761-b228-2c0c666bffa5.mp4
ENG-48127
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Popup` story behaves as expected.
=> fix: popup: fixes pseudo element so it doesn't block cursor

src/components/Button/button.module.scss, src/styles/themes/_default-theme.scss
- Moves `NeutralButton`, `SystemUIButton` and `TwoStateButton` color palettes to global CSS variables
- Moves split divider colors to global CSS variables
https://user-images.githubusercontent.com/99700808/231304214-996c0226-90f6-4ace-a0d6-451c427473fe.mp4
ENG-49421
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Button` stories behave as expected.
=> fix: button: move three more button palettes to global css vars

src/components/Pills/Pill.test.tsx, src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts, src/components/Pills/__snapshots__/Pill.test.tsx.snap, src/components/Pills/pills.module.scss, src/octuple.ts
Adds a prop to determine whether to align the `Pill` icon to the left or right of its label.
https://user-images.githubusercontent.com/99700808/231605921-2bd5d450-db3b-4b45-af16-d40db51eb10a.mp4
ENG-49604
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Pill` icon story behaves as expected.
=> feat: pill: add align icon prop

src/components/Upload/Tests/__snapshots__/uploadlist.test.tsx.snap, src/components/Upload/Tests/type.test.tsx, src/components/Upload/Upload.stories.tsx, src/components/Upload/Upload.tsx, src/components/Upload/Upload.types.tsx, src/components/Upload/UploadList/ListItem.tsx, src/components/Upload/UploadList/index.tsx
Adds `<button>` `type` props to `Upload` `showUploadList` interface and defaults them to `'button'` to prevent unintended `Form` submit
ENG-49788
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Upload` stories behave as expected.
=> fix: upload: adds button type props to show list item interface

src/components/Tooltip/tooltip.module.scss
The reference element of `Tooltip` and `Popup` were inheriting the `pointer-events: none` property and value of the reference wrapper. As the reference and base Tooltip styling concerns are separated in this regard, this is not needed. Removing this line should fix the issue where disabling Tooltips cause inputs to ignore pointer events.
ENG-50127
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `Tooltip` and `Popup` stories behave as expected when `disabled` is `true `or `false`.
=> fix: tooltip: remove pointer events property of disabled styling

src/components/Tooltip/Tooltip.test.tsx
Adds unit test validating the `Tooltip` reference element is clickable when `Tooltip` is `disabled`.
ENG-50140
Pull the PR branch and run `yarn` and `yarn test`. Verify tests succeed.
=> chore: tooltip: add disabled unit test verifying clickable element

src/components/Avatar/Avatar.test.tsx, src/components/Avatar/AvatarGroup.stories.tsx, src/components/Avatar/AvatarGroup.tsx, src/octuple.ts
fix(avatar group): avatar group count, maxProps fixes.
The maxProps count is not being properly considered to show the correct count.
Having wrong counts shown when sent as children or avatarListProps -> fixed.
Avatar Group completely null rendered or moot when the numChildren available less then maxProps set -> fixed.
https://eightfoldai.atlassian.net/browse/ENG-50821
1.) Check the below stories of Avatar Group, the earlier wrongly shown counts are properly shown and in case of the octuple stories of Exceed MaxCount than children all avatars must render inline.
=> fix(avatar group): avatar group count, maxProps fixes

src/components/Empty/Empty.stories.tsx, src/components/Empty/Empty.test.tsx, src/components/Empty/Empty.tsx, src/components/Empty/Empty.types.ts
Add descriptionClassNames property on Empty component
https://eightfoldai.atlassian.net/browse/ENG-51296
https://eightfoldai.atlassian.net/browse/ENG-51296
I need to include additional styling on the Empty component description text. The test case I've added should be sufficient to verify that this behaves as expected.
=> feat: adding style option for Empty description

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/hooks/usePreviousState.test.tsx, src/hooks/usePreviousState.ts
- Fixes `Select` focus steal on init by checking `firstRender` in the options change `useEffect`
- Fixes bug in `Dropdown` where the inherited id of the locally cloned element was being overridden by the component
- Fixes bug in smartApply where re-render caused the `defaultValue` to be `''`
- Fixes bug in smartApply where the option `role` was being overridden by `menuitem` default
ENG-51660
Pull the PR branch and run `yarn`, `yarn test` and `yarn storybook`. Verify all tests pass and the `Dropdown`, `Menu` and `Select` stories behave as expected.
=> fix: dropdown: use id from clone element props if present

src/components/Button/SystemUIButton/SystemUIButton.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
`SystemUIButton` is the only button that uses `transparent` prop, ensure it's passed down to `Button`
ENG-27605
Pull the PR branch and run `yarn`, `yarn test`, and `yarn storybook`. Verify all tests pass and the `SystemUIButton` behaves as expected.
=> chore: systemuibutton: pass transparent down via props

src/components/Stepper/Stepper.tsx
fix: stepper: prevent vertical scrollIntoView on mount
=> fix: stepper: prevent vertical scrollIntoView on mount

src/components/Button/DefaultButton/DefaultButton.tsx
`<DefaultButton/> `was updated to add a default state of `false` to `disruptive` prop, previously this prop was not being passed down to `<BaseButton />` and was updating via `{...rest}`. This change fixes the legacy default button implementations of `disruptive`
ENG-52564
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `disruptive` control of Default Button story.
=> fix: button: pass disruptive down from props to button from defaultbutton

CHANGELOG.md, package.json, src/components/Button/DefaultButton/DefaultButton.tsx, src/components/Button/SystemUIButton/SystemUIButton.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Pagination/Pager.tsx, src/components/Pagination/Pagination.stories.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/Pagination.types.ts, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Stepper/Stepper.tsx
Sync the dev branch to latest main
=> Merge main into dev

src/components/Dropdown/dropdown.module.scss
Updates `Dropdown` CSS animation to reduce time in perceptible milliseconds between execution and completion. Removes 0s delay parameter and updates Penner curves to match those used with `DatePicker`, for smoother results.
https://github.com/EightfoldAI/octuple/assets/99700808/d8fb37a1-7029-4482-8e89-c96400b7c199
ENG-53146
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Dropdown shows and hides as expected.
=> fix: dropdown: tweak css slideupin animation

src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/DateTimePicker/DatePicker/Locale/hi_IN.tsx, src/components/DateTimePicker/Internal/Generate/dayjs.ts, src/components/DateTimePicker/Internal/Locale/hi_IN.ts, src/components/DateTimePicker/TimePicker/Locale/hi_IN.tsx, src/components/Dialog/BaseDialog/Locale/hi_IN.tsx, src/components/InfoBar/Locale/hi_IN.tsx, src/components/Locale/hi_IN.tsx, src/components/LocaleProvider/Tests/__snapshots__/index.test.js.snap, src/components/LocaleProvider/Tests/index.test.js, src/components/LocaleProvider/hi_IN.tsx, src/components/Pagination/Locale/hi_IN.tsx, src/components/Panel/Locale/hi_IN.tsx, src/components/Stepper/Locale/hi_IN.tsx, src/components/Table/Locale/hi_IN.tsx, src/components/Upload/Locale/hi_IN.tsx
Add support for `hi` locale
ENG-48965
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `ConfigProvider` `Locale` story behaves as expected.
=> fix: locale: add support for hi locale

src/components/Select/select.module.scss
The updated `Pill` sizes are now the same vertical size as `TextInput`. This change ensures that when a `Pill` is presented as a child of a Multiple `Select` `TextInput`, they fit as expected.
https://github.com/EightfoldAI/octuple/assets/99700808/d83f2061-4746-4e97-9f2a-547b54ec11b3
ENG-54999
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Multiple `Select` story behaves as expected in Small, Medium and Large sizes when selecting options.
=> fix: select: ensure medium and large pills fit inside inputs of same size

src/components/Slider/Slider.tsx, src/components/Slider/slider.module.scss, src/components/Tooltip/Tooltip.tsx
- Adds a hit target element equal to the height of the `Slider` input + thumb
- Ensures track and rail events are not called twice by adding a new handler
- Ensures clicks between segments are handled when `showMarkers`
- Ensures `Slider` `Tooltip` doesn't dismiss on reference element click by default so value may be passed to it if needed.
https://github.com/EightfoldAI/octuple/assets/99700808/ece38bc6-a377-4e4a-8100-08e155508df3
https://github.com/EightfoldAI/octuple/assets/99700808/24fc4fe8-cdce-4a38-b74c-74c4351b6ddd
ENG-54321
ENG-54319
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Slider` stories behave as expected.
=> fix: slider: increase vertical hit target and handle segmented gap clicks

src/components/Select/Select.tsx
Reverts [PR 631](https://github.com/EightfoldAI/octuple/pull/631) pending further investigation of how to improve isLoading.
ENG-55821
N/A
=> fix: select: revert update selected option based on defaultValue when isLoading

src/components/MatchScore/matchScore.module.scss, src/styles/themes/_default-theme.scss
- Ensures `MatchScore` dots adhere to 3:5:1 color contrast baseline by using the latest Figma spec tertiary blue
- Fixes vertical center alignment of dots when label is present
Before:
After:
ENG-55945
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `MatchScore` stories behave as expected.
=> fix: matchscore: color contrast and vertical alignment fix up

src/components/Tabs/tabs.module.scss, src/styles/themes/_default-theme.scss
- Ensure `Tabs` `Pill` variant selected tab adheres to 3:5:1 color contrast ratio
- Adds CSS Variables
Before:
After:
ENG-55940
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `Tabs` stories behave as expected.
=> fix: tabs: pill variant color contrast fix up

src/components/Select/Select.tsx
Options array is updated to consider defaultValue in case defaultValue prop is passed. But if the options are passed asynchronously then options array might be empty when the hook runs. So to consider defaultValue prop is respected on isLoading changes we implement a separate useEffect hook that updates options on isLoading changes.
NA
NA
1. Tested previously failing seleniums are passing. [Please find recording attached.]
2. Tested the parts of code that use defaultValue with isLoading in vscode are working properly. I've tested following paths:
```
www/react/src/apps/insights/components/DataHub/SQLEditor.js
www/react/src/apps/profile/components/AddNotesTags/AddNote/index.js
```
**Video recording for seleniums that were failing in previous release PR:** …
=> fix: select: Update selected option based on defaultValue when isLoading changes

src/components/Slider/Slider.tsx, src/components/Slider/slider.module.scss
Ensure the reference wrapper is visually hidden upon `Tooltip` disabled
https://github.com/EightfoldAI/octuple/assets/99700808/be0b1093-62e7-4d45-94b1-e94b22d7c2be
ENG-56910
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Slider` disable prop behaves as expected.
=> fix: slider: ensure tooltip is visually hidden when slider is disabled

src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap
Add `htmlType` prop with a default value of `button` to `MenuItemButton`
ENG-56936
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `Menu` component behaves as expected.
=> fix: menu: add htmltype prop to menu item button

src/components/Dialog/BaseDialog/base-dialog.module.scss, src/components/Dialog/dialog.module.scss, src/components/Dropdown/dropdown.module.scss, src/components/Form/form.module.scss, src/components/InfoBar/infoBar.module.scss, src/components/Inputs/input.module.scss, src/components/Label/label.module.scss, src/components/Layout/layout.module.scss, src/components/Link/link.module.scss, src/components/List/list.module.scss, src/components/Modal/modal.module.scss, src/components/Navbar/navbar.module.scss, src/components/Pagination/pagination.module.scss, src/components/Panel/panel.module.scss, src/components/PersistentBar/persistentBar.module.scss, src/components/Select/select.module.scss, src/components/Slider/slider.module.scss, src/components/Snackbar/snackbar.module.scss, src/components/Table/Styles/table.module.scss, src/components/Tabs/tabs.module.scss, src/components/Tooltip/tooltip.module.scss, src/components/Tree/Styles/tree.module.scss, src/styles/themes/_definitions.scss
Removes `$octuple-font-family` SASS variable in favor of `var(--font-stack-full)` semantic variable.
N/A
N/A
N/A
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the font in all components.
=> chore: css: remove redundant font stack sass and use semantic variable

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- Adds options fallback to empty array where needed and some optional chaining
- Updates `placeholder` to show when `options` are null in` multiple` mode
- Adds unit tests covering null or empty array scenarios
- Updates `options` to ensure `id` alignment.
https://github.com/EightfoldAI/octuple/assets/99700808/4e1e18c7-81da-4707-be4e-10a158edfa2c
https://github.com/EightfoldAI/octuple/issues/666
ENG-58585
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Select` stories behave as expected when its `options` are `null` or `[]`.
=> fix: select: adds fall back and optional chaining to avoid null reference errors at runtime

src/components/InfoBar/InfoBar.stories.tsx, src/components/InfoBar/InfoBar.test.tsx, src/components/InfoBar/InfoBar.tsx, src/components/InfoBar/InfoBar.types.ts, src/components/InfoBar/__snapshots__/InfoBar.test.tsx.snap, src/components/InfoBar/infoBar.module.scss, src/styles/themes/_default-theme.scss
- Adds `bordered` prop to enable borders if needed
- Updates stories to add `bordered` control
- Adds unit test
https://github.com/EightfoldAI/octuple/assets/99700808/299e174d-6ce7-4ae8-a7fa-baff3695448d
ENG-59527
Pull the PR branch and run `yarn` and `yarn storybook`. Verify `InfoBar` stories behave as expected when setting `bordered` to true
=> feat: infobar: adds bordered prop

src/components/DateTimePicker/DatePicker/Styles/mixins.scss, src/components/Table/Internal/octable.module.scss
- Adds back removed default `overflow: auto;` in scroll-bars() mixins
https://github.com/EightfoldAI/octuple/assets/99700808/6aa01118-38fc-4f9c-93d6-e6b14b4ec110
ENG-59638
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Table` stories behave as expected.
=> fix: table: adds default overflow back to latest scroll bars mixin

src/components/Accordion/Accordion.test.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, src/components/Accordion/accordion.module.scss
- Adds CSS animation to help determine when to toggle its overflow-y
https://github.com/EightfoldAI/octuple/assets/99700808/1f1460de-6138-47d2-9ca9-6a1cd739383e
https://github.com/EightfoldAI/octuple/issues/674
ENG-59910
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Accordion` stories behave as expected.
=> fix: accordion: fixes scroll bar animation flicker

src/components/Card/Card.stories.tsx, src/components/Card/Card.test.tsx, src/components/Card/Card.tsx, src/components/Card/Card.types.ts, src/components/Card/__snapshots__/Card.test.tsx.snap, src/components/Card/card.module.scss
- Removes Outdated Story
- Adds `TODO` comment to add predefined card variants and update the one that currently exists
- Adds a small size (small used to map to medium via the `CardSize` enum)
- Updates padding for each size (`large`, `medium`, and `small`) to spec
https://github.com/EightfoldAI/octuple/assets/99700808/afbd8299-766a-406d-8903-16d8d0e10e24
ENG-61008
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Card` story behaves as expected.
=> feat: card: update card size prop and remove bunko story

src/components/Button/button.module.scss, src/styles/themes/_default-theme.scss
Some custom themes will update the following properties to have gradient values. Currently CSS3 transitions [do not yet support animating gradients](https://stackoverflow.com/questions/6542212/use-css3-transitions-with-gradient-backgrounds). To work around this technical limitation we're exposing the button transition as a new variable `--button-transition`. That way it may be set to have a value of `none` to avoid a 200ms flicker in scenarios where the button theme background variables use gradient values.
https://github.com/EightfoldAI/octuple/issues/692
ENG-62150
Pull the PR branch and run `yarn` and `yarn storybook` Verify the `Button` stories behave as expected.
=> fix: button: moves button transition to global semantic variables

src/components/Inputs/input.module.scss
- Adds `pointer-events: none` to grippy so it will not steal click and drag
https://github.com/EightfoldAI/octuple/assets/99700808/5ec3216b-7c35-4e0d-89dd-d3b34029ee72
https://github.com/EightfoldAI/octuple/issues/693
ENG-62761
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Text Area` story behaves as expected.
=> fix: textarea: ensure grip icon doesn't block mouse drag

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Tooltip/Tooltip.tsx
Fixes cloned element classes for `Tooltip` default variant by checking if `className` vs `classNames`. This was not necessary in previous versions because there was no need for local props.
ENG-63065
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Tooltip story behaves as expected.
=> fix: tooltip: fixes default clone element class names

src/components/Carousel/Carousel.tsx, src/components/Carousel/Carousel.types.ts, src/components/Carousel/ScrollMenu/ScrollMenu.tsx, src/components/Carousel/Tests/ScrollMenu.test.tsx, src/components/Carousel/Tests/__snapshots__/ScrollMenu.test.tsx.snap
Add `controls` prop to scroll menu so that when the `Carousel` `type` prop is set to `'scroll'` the controls props does the work to hide the next/prev buttons if desired.
https://github.com/EightfoldAI/octuple/assets/99700808/4ad5305a-8639-4020-b4d9-ba8f8bb4d548
ENG-63467
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Carousel` `Scroller` stories behave as expected when `controls` is toggled.
=> fix: carousel: add controls prop to scroll menu

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Tooltip/Tooltip.tsx
The internal class being at the beginning of the array potentially causes test bugs in production, moving `tooltip-reference` to the end of each array should fix the test bugs.
Updates 2 snaps
N/A
N/A
N/A
=> chore: tooltip: moves internal class to the end of each clone element class array

src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.stories.tsx, src/components/Inputs/SearchBox/SearchBox.test.tsx, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Inputs/Styles/rtl.scss, src/components/Inputs/TextArea/TextArea.stories.tsx, src/components/Inputs/TextArea/TextArea.test.tsx, src/components/Inputs/TextArea/TextArea.tsx, src/components/Inputs/TextInput/TextInput.stories.tsx, src/components/Inputs/TextInput/TextInput.test.tsx, src/components/Inputs/TextInput/TextInput.tsx, src/components/Inputs/input.module.scss, src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/Styles/rtl.scss, src/components/Select/select.module.scss, src/styles/themes/_default-theme.scss, src/styles/themes/_definitions.scss
- Updates `TextInput`, `TextArea`, `SearchBox` `readonly` and `readOnlyProps`, enabling complex custom readonly implementations.
- Updates Select `readonly` to behave as expected
- Adds UTs
https://github.com/EightfoldAI/octuple/assets/99700808/75995ec6-fa42-49e3-ba8f-82bcfa0c5f29
ENG-60991
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Inputs` and `Select` stories behave as expected.
=> feat: inputs: add readonly support and its styles

src/components/ConfigProvider/ConfigProvider.stories.tsx, src/components/Progress/Line.tsx, src/components/Progress/Progress.stories.tsx, src/components/Progress/Progress.tsx, src/components/Progress/Progress.types.ts, src/components/Progress/Steps.tsx, src/components/Progress/Styles/rtl.scss, src/components/Progress/Tests/__snapshots__/index.test.tsx.snap, src/components/Progress/Tests/index.test.tsx, src/components/Progress/progress.module.scss, src/styles/themes/_default-theme.scss
- Adds `ProgressVariant` enum with `Default` and `Pill`
- Adds `variant` prop support for `Line` and `Step` `ProgressType`
- Adds `Large` `ProgressSize`
- Adds `pillBordered` prop to show/hide a border on the outer element
- Adds CSS Variables
- Adds Unit tests
- Updates colors to latest spec
- Updates Storybook with additional Pill variant stories
https://github.com/EightfoldAI/octuple/assets/99700808/c40af8d2-0d91-4dfa-a7fa-04b05d770738
ENG-61012
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Progress` stories behave as expected.
=> feat: progress: add pill variant

src/components/Button/Button.tsx
Before:
After:
ENG-65559
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Button` `Counter` story by removing the button text.
=> fix: button: fixes counter position when button only contains an icon

src/components/LinkButton/LinkButton.tsx
Before:
After:
ENG-65559
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `LinkButton` `Counter` story by removing the button text.
=> fix: linkbutton: fixes counter position when button only contains an icon

src/components/Card/Card.stories.tsx, src/components/Card/Card.test.tsx, src/components/Card/__snapshots__/Card.test.tsx.snap, src/components/Card/card.module.scss
This update corrects the card component to use the semantically named card-border-color instead of the generic border-color
https://github.com/EightfoldAI/octuple/issues/701
- pull down PR code
- run storybook
- in the card story, turn off dropshadow and turn on bordered
- ensure card has a border color
- inspect the element and confirm it is now using a semantic css vawriable
=> fix: use semantic card border color for cards

src/styles/themes/_default-theme.scss
- Updates `--anchor-neutral-hover-color` to `--grey-secondary-color`
- Updates `--anchor-secondary-hover-color` to `--grey-color-90`
ENG-52998
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the above link colors.
=> fix: link: align two hover colors with the latest design spec

src/components/Upload/Upload.tsx
Compares for tab key on button keydown
https://github.com/EightfoldAI/octuple/issues/725
- [] Tests for this change already exist
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Dropzone does not trap keyboard focus upon tabbing around.
=> fix: dropzone: ensures tab key event is not prevented

src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Panel/__snapshots__/Panel.test.tsx.snap
- Compare for `footer` via props and return one only if needed.
- Adds UT
- Updates Stories
https://github.com/EightfoldAI/octuple/issues/687
Pull the PR branch and use the PR Codesandbox to verify behavior.
=> fix: panel: ensures there is no element when footer is not implemented

src/components/Avatar/Styles/group.scss, src/components/Avatar/avatar.module.scss
- Updates css selector property `background-color` to `background` to support more theme possibilities
- Updates theme color set from `tertiary` to `secondary` base palette to ensure 4:5:1 conformance
ENG-63968
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Avatar` and `AvatarGroup` stories behave as expected.
=> fix: avatar: update background theme colors from tertiary to secondary

src/shared/FocusTrap/hooks/useFocusTrap.test.tsx, src/shared/FocusTrap/hooks/useFocusTrap.ts
- Move away from `setTimeout` to a commonly used `setInterval` with `clearInterval` with `useEffect` cleanup when the `activeElement` requirement is fulfilled pattern, this greatly improves the reliability because waiting for 100ms only and executing `focus()` once is not very robust in `async`
- Updates `isShiftPressed` to actually do its job
- Adds optional chaining
- Adds missing types
- Adds Unit Tests
https://github.com/EightfoldAI/octuple/issues/733
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Dialog`, `Modal` and `Panel` stories behave as expected using keyboard only. Be sure to visit the `ConfigProvider` `Theming` story first, tab around to active `focus-visible`
=> fix: focustrap: improve reliability of use focus trap hook

src/components/FadeIn/FadeIn.stories.tsx, src/components/FadeIn/FadeIn.test.tsx, src/components/FadeIn/FadeIn.tsx, src/components/FadeIn/FadeIn.types.ts, src/components/FadeIn/index.ts, src/octuple.ts
- Add `FadeIn` component
- Add its Unit Tests
- Add its story
https://github.com/EightfoldAI/octuple/assets/99700808/32ebadb1-e692-4664-a26b-c4eb1d346a7a
ENG-62741
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `FadeIn` component behaves as expected.
=> feat: fadein: add fadein component

src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx
- Adds event listener to trigger toggle upon escape keydown
https://github.com/EightfoldAI/octuple/assets/99700808/0666a92f-3a74-47bc-a0f2-85d05aab34dd
ENG-63973
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Tooltip` story behaves as expected.
=> fix: tooltip: escape to dismiss default tooltip on hover only

src/components/InlineSvg/InlineSvg.test.tsx, src/components/InlineSvg/InlineSvg.tsx
- memoizes `fetchSvg` with managed url
- Only execute fetchSvg if the current url is different than the previous url
https://github.com/EightfoldAI/octuple/issues/711
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `InlineSVG` story behaves as expected.
=> fix: inlinesvg: memoized fetch and compare with previous url

src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/Breadcrumb.types.tsx, src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
- extend `Breadcrumb` to have custom divider and custom crumbs
N/A
https://eightfoldai.atlassian.net/browse/ENG-68572
Pull the PR branch and run yarn and yarn storybook. Verify the Breadcrumb component has the following story:
=> feat: extend breadcrumb for custom divider and crumb

src/components/Menu/MenuItem/menuItem.module.scss, src/components/Skill/SkillBlock.tsx, src/components/Skill/skill.module.scss
Reverts global inset change to `menuItem.module.scss` and scopes inset to `skill.module.scss`.
ENG-53012
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Menu` and `SkillBlock` stories behaves as expected.
=> chore: skill: revert custom menu item and replace with scoped change

src/components/Button/button.module.scss
Prior to this change Icon-only `Button` of `variant` `ButtonVariant.Secondary`, with a `shape` of `ButtonShape.Round` were distorting by 1px in all sizes. This change updates this flavor of button so its perfectly round.
https://github.com/EightfoldAI/octuple/assets/99700808/46114994-e56c-4c03-92e0-f8cce6d1d45b
ENG-69418
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Button` `Secondary` story behaves as expected with only an icon and round shape in all sizes.
=> fix: button: fixes round icon only secondary buttons padding to consider its border

src/components/Popup/Popup.stories.tsx, src/components/Popup/Popup.tsx, src/components/Popup/Popup.types.ts, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/components/Tooltip/tooltip.module.scss, src/hooks/useGestures.test.tsx, src/hooks/useGestures.ts, src/octuple.ts
Fixes `Popup` and `Tooltip` with a `trigger` of `hover` interaction on mobile and Hybrid devices. `Popup` defaults to `Tap`, `Tooltip` to `TapAndHold` when using a finger, hover when using mouse on hybrid. Also fixes some additional A11y bugs.
- Adds and exports `useGestures` Hook and its `Gestures` enum to include `SwipeDown`, `SwipeLeft`, `SwipeRight`, `SwipeUp`, `Tap`, and `TapAndHold`
- Adds `touchInteraction`, `disableContextMenu` props to `Tooltip` and `Popup`
- Adds `TooltipTouchInteraction`, and `PopupTouchInteraction` and exports them so the touch trigger may be determined at implementation time
- Updates `Tooltip` so that when its trigger is `hover` and a user is touching the `touchInteraction` will determine whether `Tap` or `TapAndHold` will toggle the `Tooltip` or `Popup`, …
=> feat: tooltip: adds touch api support with hover a11y fixup

src/hooks/useGestures.test.tsx, src/hooks/useGestures.ts
Test for touch start positions before setting gesture to null on mouse move.
NA
ENG-70944
- [] Feature Pull Request
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Popup` and `Tooltip` stories behave as expected.
=> chore: usegestures: test for touch start positions in onmousemove

src/components/Tooltip/tooltip.module.scss
Removes cursor styles from `Tooltip` and `Popup` such that they are deferred to implementation.
ENG-71954
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Popup` and `Tooltip` stories behave as expected.
=> fix: tooltip: defer cursor style to implementation in host app

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Tooltip/Tooltip.tsx
Removes missed class name references to `styles.disabled`, no longer needed and causes compiler errors with a clean build.
ENG-71954
N/A
N/A
N/A
=> chore: tooltip: removes no longer existing disabled class name references

src/components/Carousel/Carousel.stories.tsx, src/components/Carousel/Carousel.tsx, src/components/Carousel/index.ts, src/octuple.ts
- Adds `autoScrollApi` and `autoScrollApiType` to exports, improving advanced scenario support for `Carousel` `scroll` mode
- Updates existing `Carousel` `scroll` mode stories to use `Card` component at a size commonly used in Eightfold applications
- Adds story demonstrating custom next/previous button implementation using `autoScrollApi` and `autoScrollApiType`  in a constrained `Card` layout
- Removes unreferenced `style` prop from `Carousel`
https://github.com/EightfoldAI/octuple/assets/99700808/f86b2c55-df10-4765-a8b6-865066f727c5
ENG-72093
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Carousel` stories behave as expected.
This [Codesandbox](https://codesandbox.io/p/sandbox/eager-haze-mg3t48?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootP …
=> feat: carousel: exports autoscrollapi and updates story to include custom buttons example

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/List/List.test.tsx, src/components/List/List.tsx, src/components/List/List.types.ts, src/components/List/__snapshots__/List.test.tsx.snap, src/components/Menu/CascadingMenu.test.tsx, src/components/Menu/CascadingMenu.tsx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.test.tsx, src/components/Menu/Menu.tsx, src/components/Menu/Menu.types.ts, src/components/Menu/MenuItem/MenuItem.tsx, src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx, src/components/Menu/MenuItem/MenuItemCustom/MenuItemCustom.tsx, src/components/Menu/MenuItem/MenuItemLink/MenuItemLink.tsx, src/components/Menu/MenuItem/MenuItemSubHeader/MenuItemSubHeader.tsx, src/components/Menu/__snapshots__/CascadingMenu.test.tsx.snap, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/octuple.ts, src/shared/FocusTrap/hooks/useFocusTrap.ts, src/shared/utilities/types.ts
This change adds `ArrowDown`, `ArrowLeft`, `ArrowRight`, and `ArrowUp` keyboard navigation support to address existing usability bugs in `List`, `Dropdown`, `Menu`, `CascadingMenu`, and `Select` components.
- Moves `SELECTOR` string from `useFocusTrap` scope to utility scope so that it may be used by `List`
- Adds `focusable` function that returns true if certain attributes exist on element passed into it via args
- Adds arrow key support to `List` component via its new `handleItemKeyDown` function
- Updates `List` `getItem` prop implementation to be wrapped in `externalItem` so that we can access its properties
- Updates `List` `getAdditionalItem` such that it may be included in the focus loop
- Updates `List` to include an option to disable default arrow key handling via …
=> feat: a11y: arrow key navigation support for list menu dropdown and select

src/components/Slider/Slider.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/hooks/useGestures.ts
- Provides a argument (`preventTouchMoveDefault`) to determine if `touchmove` should be handled in `useGesture`
- Applies fix to Slider so the thumb may be dragged on mobile again
ENG-75094
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Slider` stories behave as expected on touch screen by dragging the thumb.
=> fix: slider: ensure touchmove is not prevented to enable default touch on mobile

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Skill/Tests/__snapshots__/SkillBlock.test.tsx.snap, src/components/Skill/Tests/__snapshots__/SkillTag.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx
- Dedupes `tooltipId`
- Adds `tooltipWrapperID`
- Updates story to work with screen readers via `tabIndex` and `aria-describedby` changes
https://github.com/EightfoldAI/octuple/assets/99700808/84ab67d6-98f3-44b5-9ccc-a4e9744a11cf
https://github.com/EightfoldAI/octuple/issues/763
ENG-74737
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Tooltip` story works as expected using VoiceOver.
=> fix: tooltip: dedupes tooltip id and updates story for screen readers

src/components/DateTimePicker/DatePicker/Styles/status.scss, src/styles/themes/_default-theme.scss
- Updates the default text validation status input font colors to `--text-primary-color` so they are consistent with invalidated state, deferring visual cue to its border and inline validation text
ENG-65381
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Form` stories behave as expected.
=> fix: input: updates validation status font color to latest specification

src/components/Table/Hooks/useSelection.tsx
- Adds missing `indeterminate` state to check all `CheckBox` when only some rows are checked
https://github.com/EightfoldAI/octuple/assets/99700808/e0031889-6999-4fbd-8972-b0cda7b45843
ENG-75615
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Table` stories behave as expected.
=> fix: table: adds indeterminate state to check all box if only some rows are selected

src/components/LinkButton/linkbutton.module.scss
Currently, `LinkButton` picks up a few styles from Bootstrap, this change should prevent that happening.
- Prepends `a` to selectors (e.g. `a.link-button {...}`)
- Updates a few selector `background-color` properties to `background`
https://github.com/EightfoldAI/octuple/assets/99700808/1ab2cea0-5c1a-4c3e-95d2-e82faf2d5911
ENG-76763
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `LinkButton` stories behave as expected. For further validation update your local vscode build that uses global Bootstrap CSS to reference the PR package and verify the styles.
=> fix: linkbutton: adjust anchor specificity to ignore bootstrap styles

src/components/Icon/Icon.tsx, src/components/Table/Table.tsx, src/shared/ResizeObserver/ResizeObserver.tsx, webpack.common.js
Currently with every semver merged into vscode apps, the snapshot tests reflect a partial guid representing the function names in Octuple (e.g. `<Xw />`), this change ensures function names are not minified so the snaps should not need to be updated with each version bump.
ENG-77343
Pull the PR branch and run `yarn` and `yarn storybook`. Verify components behave as expected. Then follow the steps in the internal wiki to create your own tarball, install is in vscode react project and run the project, then execute `npm run test:update` Note that the function names are no longer minified and should persist from version to version. There may be one failing vscode unit test (DropdownWrapper), but that one is fixed, pending merge in v2.48.0 and is to be expected.
=> fix: upstream: ensures upstream snaps do not minify function component names

src/components/Table/ExpandIcon.tsx, src/components/Table/Internal/Body/BodyRow.tsx, src/components/Table/Internal/Cell/index.tsx, src/components/Table/Internal/OcTable.tsx, src/components/Table/Internal/OcTable.types.ts, src/components/Table/Internal/Tests/ExpandRow.test.js, src/components/Table/Internal/octable.module.scss, src/components/Table/Styles/mixins.scss, src/components/Table/Styles/rtl.scss, src/components/Table/Styles/size.scss, src/components/Table/Styles/table.module.scss, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/Tests/Table.expand.test.tsx, src/components/Table/Tests/__snapshots__/Table.expand.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.filter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.fixselectionexpandonleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionleft.shot, src/components/Table/Tests/__snapshots__/Table.fixselectionwithcols.shot, src/components/Table/Tests/__snapshots__/Table.pagination.accepttrue.shot, src/components/Table/Tests/__snapshots__/Table.pagination.nocrashonchange.shot, src/components/Table/Tests/__snapshots__/Table.pagination.position.shot, src/components/Table/Tests/__snapshots__/Table.pagination.renders.shot, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Table/Tests/__snapshots__/Table.test.js.snap, src/components/Table/Tests/__snapshots__/Table.usecolselectionwithkey.shot, src/components/Table/Tests/__snapshots__/empty.render.shot, src/components/Table/Tests/__snapshots__/empty.renderfixedcols.shot
- Updates default Expand Icon `Button` to match latest UX specifications
- Updates Tree indentation to include the button in the indent
- Fixes `expandIcon` prop so that custom expand cell content may be used along with a custom expand icon button
- Adds new story demonstrating custom `expandIcon`
- Separates CheckBox and Radio Selection stories to better communicate the options
- Ensures the Selection component is horizontally centered in its cell
- Updates UTs
Before:
https://github.com/EightfoldAI/octuple/assets/99700808/ba7594e2-8ce4-49e7-80ea-582782a051c6
After:
https://github.com/EightfoldAI/octuple/assets/99700808/df14636c-a21c-4328-85e9-c7b5e5d4c0a1
ENG-76971
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Table` stories behave as expected.
=> feat: table: expandable config improvements

src/components/Tabs/Stat/Stat.tsx, src/components/Tabs/StatTabs.stories.tsx, src/components/Tabs/Tabs.context.tsx, src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.types.ts, src/components/Tabs/Tabs/AnimatedTabs.tsx, src/components/Tabs/Tabs/index.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/components/Tabs/tabs.module.scss, src/styles/themes/_default-theme.scss
- Adds `direction` prop for `horizontal` or `vertical` support to `stat` `variant`
- Adds `fullWidth` prop support `vertical' `stat`
- Adds `maxWidth` prop support for `stat` `variant`
- Adds `lineClamp` prop for `stat` `variant`
- Polishes border radius and insets for `stat` so they properly handle no border and no divider scenarios as well as map to the latest spec
- Adds border radius CSS vars and removes unused vars
- `--stat-tab-border-radius-m: 40px;`
- `--stat-tab-border-radius-s: 24px;`
- `--stat-tab-border-radius-xs: 16px;`
- Updates stories
- Adds UTs
https://github.com/EightfoldAI/octuple/assets/99700808/4107d4fa-8dc2-4c5b-9f1a-bb5b52a010c6
ENG-77353
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Tabs` and `Stat Tabs` stories behave as expected.
=> feat: stat: adds direction lineclamp fullwidth and maxwidth props

src/components/Form/FormItemLabel.tsx, src/components/Form/form.module.scss
Backports v2.48.1 hotfix into main
=> fix: form: ensure form item label custom node content display is inline

src/components/List/List.stories.tsx, src/components/List/List.tsx, src/components/List/List.types.ts, src/components/List/ListItem/ExternalListItem.tsx, src/components/List/ListItem/ListItem.types.ts, src/components/List/ListItem/index.ts
the `uniqueId` helper implements a `useMemo` hook. This caused an issue where the `externalItem` function of `List` raised React errors regarding hooks.
- Abstracts out to `ExternalListItem` so useMemo will work as expected
- Refactors `List` to consume `ExternalListItem`
- Updates stories to include a `List` `Update` story where you may Add/Remove list items from `List`
https://github.com/EightfoldAI/octuple/assets/99700808/ed99253d-8723-4f75-81e5-f645b1963d72
ENG-81890
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `List` stories behave as expected.
=> fix: list: move external item into its own function component to address hook bug

src/components/Card/Card.stories.tsx, src/components/Card/Card.tsx, src/components/Card/Card.types.ts, src/components/Card/card.module.scss, src/components/Dropdown/Dropdown.types.ts, src/components/Inputs/Input.types.ts, src/components/Inputs/SearchBox/SearchBox.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Skill/SkillTag.tsx, src/octuple.ts
- Adds aria label props and placeholders to `Select` and `Input` buttons
- Adds `focus-visible` styles to `Card` and an `insetFocusVisible` prop
- Loosens-up `role` prop of `SkillTag` to consider select scenarios
- Makes `children` prop of `Dropdown` optional and marks it as deprecated
- Adds `role` prop to `SearchBox` so that it may be configured
- Exports CheckBoxValueType
ENG-84999
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Card`, `Select`, `SearchBox`, `SkillTag`, `TextInput`, and `Dropdown` stories behave as expected.
=> fix: a11y: card focus visible styles and aria label placeholders with additional code cleanup

src/components/Accordion/Accordion.tsx
- Fixes issue where the prop was not being referenced as intended
ENG-84999
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Accordion` story behaves as expected.
=> fix: accordion: ensure expand button props are passed down to the button

MANIFEST, package.json, src/components/LocaleProvider/index.tsx, yarn.lock
`memoize-one` dep contains a line referencing `globalThis` and falls back to `global` and `self`. This was incompatible with SSR, so I replaced it with logic that accomplishes the same memoization goal.
ENG-85282
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `ConfigProvider` `Locale` story behaves as expected.
=> fix: ssr: remove memoizeone dep and replace it with local function in locale

src/components/Menu/Menu.test.tsx, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx
The `onClick` event was deferred to the `...rest` spread via `MenuItemButton` props, this caused a regression in `Menu` as the `onClick` callback was being used internally to trigger `Menu` `onChange` callback upstream.
BEFORE FIX:
https://github.com/EightfoldAI/octuple/assets/99700808/e1cebfff-6772-45c4-895e-072e7751eb24
AFTER FIX:
https://github.com/EightfoldAI/octuple/assets/99700808/87acf590-855b-4c8a-8eb0-fcc3a2eb27e8
ENG-85650
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Menu` stories behave as expected.
=> fix: menu: adds onclick handler back to main button when secondarybuttonprops fixing menu onchange

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.test.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/Accordion.types.ts
- Adds `renderContentAlways` prop to `Accordion`, improving keyboard and assistive tech usability config upstream
- Adds UTs
- Updates Stories
We useEffect to first check if `renderContentAlways` is `true`. If it is, we set `shouldRender` to `true` and skip the rest of the checks. If `renderContentAlways` is `false`, we then check if `expanded` is `true`. If it is, we set `shouldRender` to `true` and clear any existing timeout. If `expanded` is `false`, we start a timeout that sets `shouldRender` to `false` after `400ms`, affording time for the animation to complete.
https://github.com/EightfoldAI/octuple/assets/99700808/ca9a3c01-b74a-4f85-8772-2d2675a7ecc4
ENG-86284
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Accordion` stories behave as expected.
=> feat: accordion: adds rendercontentalways prop managed by expanded

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/Select.types.ts, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Select/select.module.scss
- Adds `value` prop, making life a bit easier enabling scenarios like a shared upstream state or externally controlled state to determine the value of the `Select` `TextInput`, along with its selected option determined by the value of `SelectOption` desired
- memoizes `selectInputProps`, `getSelectedOptionValues` and `getSelectedOptions`
- Adds `maxPillCount` `boolean` prop. When `multiple`, and `maxPillCount` is `true`, the `Pill` don't wrap and those that cannot be displayed are represented by a count `Pill`. When `multiple` and `maxPillCount` is `false`, the `Pill` wrap
- When `Select` is multiple, the `Pill` now render in the order selected and the date returned by `Select` also reflects that order
- Adds `toggleOptions` `boolean` prop. When `false` and `Select` is not `multiple`, its …
=> feat: select: performance optimizations and features

src/components/Drawer/Drawer.stories.tsx, src/components/Drawer/Drawer.test.tsx, src/components/Drawer/Drawer.tsx, src/components/Drawer/drawer.module.scss
- Enables `maskClosable` and `overlay` props for Hint variant
- Refines overlay hide animation
https://github.com/EightfoldAI/octuple/assets/99700808/7ce0865f-70ea-4322-8a29-b0122d8c7c7d
ENG-87178
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Drawer` stories behave as expected
=> chore: drawer: makes overlay configurable for all variants

src/locale.ts
- Exports the `useLocaleReceiver` hook via locale.ts to assist in mapping localized text by component.
ENG-87175
N/A
=> chore: locale: exports uselocalereceiver hook

README.md
img.badgesize.io is down indefinitely due to it's domain being expired. Not sure if it'll ever be live again.
Move to use static badges for now with urls.
https://github.com/ngryman/badge-size/issues/113
N/A
N/A
Open the badge urls using a browser.
=> chore: readme: updates size badges

src/components/Carousel/Carousel.stories.tsx, src/components/Carousel/Carousel.tsx, src/components/Carousel/Tests/Slide.test.tsx, src/components/ConfigProvider/ConfigProvider.test.tsx, src/components/ConfigProvider/ConfigProvider.tsx, src/components/ConfigProvider/ConfigProvider.types.ts, src/components/ConfigProvider/ParentComponentsContext.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/Tooltip.types.ts, src/hooks/useTruncate.tsx, src/octuple.ts
- Fixes an issue on mobile / touch devices where the tooltip `preventTouchMoveDefault` behavior would prevent carousels from being draggable.
- Fixes the JSDoc annotation for the tooltip `touchInteraction` prop to correctly reflect the default: `TooltipTouchInteraction.TapAndHold`
> NOTE: Once this is released in a new version, https://github.com/EightfoldAI/vscode/pull/58487 and https://github.com/EightfoldAI/vscode/pull/58660 can & should be reverted. 
N/A
https://eightfoldai.atlassian.net/browse/ENG-86212
Load the Octuple storybook for Carousel on a mobile device, or on desktop using the mobile view inside of the Chrome Dev Tools (`⌘ ⇧ M`)
In the new "Scroller with Tooltips" story:
=> fix: carousel and tooltip: preventTouchMoveDefault false for tooltips inside carousels 

src/components/Tabs/tabs.module.scss
Updates Stat Tabs layout fixing line clamp word break bug and insets. Addresses TODOs noted [here](https://github.com/EightfoldAI/vscode/blob/master/www/react/src/apps/careerHub/profile/components/ProfileSuccessionsDetailsWidget/SkillAssessmentViewer.module.scss#L3-L28).
- Removes horizontal `padding` when `bordered` is `false`, but preserves vertical `padding` to preserve existing layouts
- Removes internal `margin-left` and `margin-right` from first and last `Stat` when `bordered` is `false`
- Moves `word-break: break-all;` to only apply when `lineClamp` is active
Before:
After:
ENG-87058
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Stat Tabs` stories behave as expected.
=> fix: tab: fixes stat tabs word wrap and spacing when border is false

MANIFEST, global.d.ts, package.json, src/components/Align/Align.tsx, src/components/Table/Hooks/useFilter/FilterDropdown.tsx, src/shared/utilities/index.ts, src/shared/utilities/isEqual.test.ts, src/shared/utilities/isEqual.ts, yarn.lock
- Removes [@ngard/tiny-isequal](https://www.npmjs.com/package/@ngard/tiny-isequal) dependency
- Replace with a local, transcribed utility function
- Removes old hacked type definition (my bad)
ENG-90064
Pull the PR branch and run `yarn` and `yarn storybook`. Test the `DatePicker` stories behave as expected.
=> fix: isequal: remove dep and replace with utility function derivation

src/components/Table/Internal/Body/BodyRow.tsx
In JavaScript and TypeScript, the `&&` operator is used for logical AND operations, but it can also be used for conditional rendering in React. The expression `A && B` will return `B` if `A` is truthy, and `A` otherwise.
In this case, `rowSupportExpand && expanded && expandRowNode` will render `expandRowNode` if both `rowSupportExpand` and `expanded` are truthy. If either of them is falsy, it will render that falsy value.
The reason we're seeing a "0" in some upstream bundles could be that either `rowSupportExpand` or `expanded` is `0`. In JavaScript, `0` is considered a falsy value, so if `rowSupportExpand` or `expanded` is `0`, the whole expression will evaluate to `0`.
To fix this, we ensure that `rowSupportExpand` and `expanded` are always boolean values. If they're not, we convert …
=> fix: table: ensure boolean types in react render when expandable row

src/components/Progress/Progress.stories.tsx, src/components/Tooltip/tooltip.module.scss
Reverts one line of css and a patch to a `Progress` story, upon further review there were a couple other scenarios this change regressed, so might need to wait for v3.0.0
N/A
N/A
Pull the PR brach and run `yarn` and `yarn storybook`. Verify the following stories behave as expected: `Progress` `Success Segment` and `Table` `Ellipsis with Tooltip`.
=> chore: tooltip: revert width css change

package.json, src/components/InlineSvg/InlineSvg.test.tsx, src/components/InlineSvg/InlineSvg.tsx, yarn.lock
The fetch API is supported by browsers, but when running Jest using older Node versions, it throws null reference errors as the API is not supported. The [cross-fetch](https://www.npmjs.com/package/cross-fetch) dep fixes this.
ENG-91718
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `InlineSvg` stories behave as expected.
=> fix: inlinesvg: adds cross fetch dep to avoid fetch api reference errors

src/components/Accordion/Accordion.tsx, src/components/Accordion/Accordion.types.ts, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
This change takes the toggle button out of the tabIndex and gives it a presentation role, relying on the full header click area to provide keyboard support and focus for the accordion toggle. it also points to the header content as a describedBy so its read in addition to the generic button label. Both of these can be overwritten on a case-by-case basis.
https://github.com/EightfoldAI/octuple/issues/866
- pull branch down locally and start storybook (`yarn storybook`)
- with screen reader on, use tab key to interact with accordion to observe improvements in behavior
=> fix: stop screenreaders from reading duplicate accordion toggle btns

package.json, src/components/InfoBar/InfoBar.types.ts, src/components/Skill/Skill.types.ts, src/components/Stepper/Stepper.types.ts, src/components/Tooltip/Tooltip.types.ts, yarn.lock
Fixes some type errors that were blocking storybook from running in development as a result of upgrading `@types/react` in #803.
Causes:
- A new `content` prop was added to all HTML elements in @types/react. This is defined to be a `string` upstream (I believe for the `<meta>` tag specifically), and overriding it with `React.ReactNode` failed after upgrading.
- @types/react-dom was not previously upgraded which broke typechecking on the Portal component.
Running `yarn storybook` in dev should work successfully.
=> fix: type errors & storybook

src/components/Upload/Cropper/EasyCrop.tsx, src/components/Upload/Cropper/cropper.module.scss
Added a hidden section for announcing zoom/rotate values
Jira task - https://eightfoldai.atlassian.net/browse/ENG-95132
- pull branch down locally and start storybook (yarn storybook)
- with screen reader on,  zoom and rotate the image and observe the zoomed/rotated values being announced.
=> Added a hidden section for announcing zoom/rotate values

src/components/ConfigProvider/ConfigProvider.test.tsx, src/components/ConfigProvider/ConfigProvider.tsx, src/components/ConfigProvider/ConfigProvider.types.ts, src/components/ConfigProvider/FeatureFlagProvider.tsx, src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Panel/Panel.types.ts
Add a feature flag config for octuple which can provide a mechanism to provide default behavior for Octuple components.
This adds a feature flag config, and creates one flag that can control the way that Panels are rendered
Open the panel in storybook, and toggle the `lazyLoadPanelContent` flag in the settings. You should be able to see that the panel contents are rendered or not rendered even when the panel is not visible
=> feat: feature flags: Add feature flag config for Octuple

src/components/Form/Form.stories.tsx, src/components/Form/Tests/index.test.js, src/components/Select/Select.tsx
This fix addresses the issue of Selected list item getting unselected when expanded or focus is on select dropdown container.
when keydown is called when enter is pressed on select dropdown. onClick event listener for close button on the selected pill item is getting called causing the selected item to remove from the selected list.
Fixed the issue by adding if guard to call toggle function only when currently active element in document is contained to the target close button.
https://eightfoldai.atlassian.net/browse/ENG-95192
- Pull the PR branch locally and run `yarn storybook`. 
- Verify the new added Form multiple select story on form and confirm selected items are not getting removed after expanding the select dropdown. (`http://localhost:2022/?path=/story/form--form-select-multiple`) …
=> fix: select: address selected items getting unselected when expanded.

src/components/Inputs/Input.types.ts, src/components/Inputs/TextInput/TextInput.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
This removes focusability from the button in Select components. This resolves an accessibility and usability issue in which the Select component input is focusable in order to open the dropdown, and the button provides unnecessary duplication of that action.
- Pull down code
- run storybook
- confirm that select component still works as desired:
- can open the dropdown while keyboard focused on the input 
- can open the dropdown by click on the input and/or the toggle button
=> fix: select: remove toggle button from tab order

src/components/Avatar/Avatar.tsx
Fixed tabIndex issue from Avatar component 
https://eightfoldai.atlassian.net/browse/ENG-103344
TabIndex can be controlled from props , 
if prop not passed , tabIndex is set to 0 .
=> ENG-103344: Fixed tabIndex issue from Avatar component

src/components/Form/Form.tsx, src/components/Form/Hooks/useForm.ts
fixed an issue with focus not moving to 1st required input on error.
Jira task - https://eightfoldai.atlassian.net/browse/ENG-107285
- pull branch down locally and start storybook (yarn storybook)
- with screen reader on, goto form component.
- Submit an empty form with required fields and observe that focus is moving or getting activated on the 1st empty input required field.
=> fix: formError: fixed focus not moving to 1st required input on error

src/components/Snackbar/Snackbar.stories.tsx, src/components/Snackbar/Snackbar.test.tsx, src/components/Snackbar/Snackbar.types.ts, src/components/Snackbar/snack.ts
1. The snack.serve will now use the id from SnackBarProps (if supplied). 
2. snack.serve (and related) will now return a close callback.
https://eightfoldai.atlassian.net/browse/ENG-112136
1. Run the storybook - `yarn storybook`
2. In the relevant section - http://localhost:2022/?path=/story/snack-bar--closable: make sure that you can serve multiple snacks, and close them from either the snack, or the close button. 
1. If a snack is closed from "X" icon, the ID still lives in the component state, and will have to be removed using the close snack button.
=> fix: snack: Use ID from SnackBarProps and return a close callback fn

src/components/Pills/pills.module.scss
The `pointer-events: none` CSS is causing NVDA to not read the pills. To make our pill component accessible, we will remove it from Octuple and will override in the apps if needed.
https://eightfoldai.atlassian.net/browse/ENG-103348
1. Run storybook with `yarn storybook` 
2. Go to pills, and make sure each pill is readable by NVDA once you click on it.
=> fix: pills: Remove pointer-events: none from readonly pill

src/components/Dropdown/Dropdown.tsx, src/components/List/List.test.tsx, src/components/List/List.tsx, src/components/List/__snapshots__/List.test.tsx.snap, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
The Select Component in octuple internally uses DropDown and List component to show the list of options. Fixing the following a11y issues found by Axe Devtools in Select component:-
1.  Inside the `Select` component, the dropdown div is the parent of list (ul/ol) but both contain `role="listbox"`. This raises an issue that listbox role could not be inside another listbox role. Hence giving the `role="group"` for outer div.
2.  Inside the `Select` component, the aria-label is missing from the input field list (ul/ol) which has the role="listbox". This is because correct `id` has not been passed onto the `<ul>` element so it could be corrected labeled by the `<input>` element using `aria-controls`.
https://eightfoldai.atlassian.net/browse/ENG-110373
1. Run storybook with yarn storybook
2. …
=> feat: [Select] make dropdown role=group and pass correct id to options list for a11y

src/components/DateTimePicker/Internal/Partials/DecadePartial/Decade.tsx, src/components/DateTimePicker/Internal/Partials/MonthPartial/Month.tsx, src/components/DateTimePicker/Internal/Partials/QuarterPartial/Quarter.tsx, src/components/DateTimePicker/Internal/Partials/YearPartial/Year.tsx
Support onKeyDown for Partials in the Datepicker for Month, Quarter, Decade and Year
https://eightfoldai.atlassian.net/browse/ENG-116348
1. Run Storybook.
2. GO to the DatePicker component with Trap Focus
3. Using Keyboard tab into the component and then make sure the up, down and arrow keys can navigate the layout
4. Select a date and it should be selected and closed.
=> fix: auto close date picker after selection

src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx
Dropdown element is clicking on first element since instead of focus, we were calling onclick event
https://eightfoldai.atlassian.net/browse/ENG-116631
1. Go to storybook
2. Go to Dropdown, Single Dropdown
3. Use Keyboard to Tab and when you tab multiple times it should not close or click on the element
=> fix: dropdown auto click the element when TAB operation is invoked

src/components/InlineSvg/InlineSvg.test.tsx, src/components/InlineSvg/InlineSvg.tsx
Revert the usage of cross-fetch in InlineSvg and use fetch only
na
https://eightfoldai.atlassian.net/browse/ENG-116802
InlineSvg should still work
=> [fix] revert InlineSvg changes

src/components/Dropdown/Dropdown.tsx
There was a bug introduced recently to make the focus of the dropdown sticky.
This regressed any input fields to be stuck on first focus
https://eightfoldai.atlassian.net/browse/ENG-116631
1. Go to storybook
2. Check the Dropdown Advanced
3. Make sure you can tab into the checkbox
https://github.com/user-attachments/assets/93450c52-aed9-4ff6-8b71-15c8da1bf6ab
=> fix: dropdown items are not moving to the next tab index due to stopPropagation

src/components/Button/button.module.scss
- When checked prop is true for 2 state button , the loader background is default and not button background
https://eightfoldai.atlassian.net/browse/ENG-121243
- Visit storybook for `TwoStateButton`
- Toggle loading to True
- toggle checked to True, before vs after
- Regression test: checked false, loading true, etc ...
=> [fix] [two state button] loader background color inconsistent when checked

src/components/Table/Internal/Body/Scroller.tsx
Left scroller button in Table row interrupts with mouse events like hover popup, even when it is not visible.
https://eightfoldai.atlassian.net/browse/ENG-121104
1. pull branch down locally and build and sync with vscode octuple module under node modules.
2. Verify the hover on Demand pipeline page of resourcing.
=> fix: scroller is interrupting with the mouse events even when it is not visible

src/components/Inputs/SearchBox/SearchBox.tsx
Added default prop role as "combobox" for Searchbox Component
https://eightfoldai.atlassian.net/browse/ENG-120699
Updated role "combobox" to SearchBox component , verify role for searchbox component inside storybook
=> ENG-120699: Added default role:'combobox' for Searchbox component

src/components/DateTimePicker/DatePicker/DatePicker.stories.tsx, src/components/DateTimePicker/Internal/OcPicker.types.ts, src/components/DateTimePicker/Internal/OcRangePicker.tsx
- The aria-label was applied only to the wrapper div element, representing the entire group.
- Inside the wrapper div, there are two input fields: one for the start date and one for the end date.
- To improve accessibility, we added support for custom aria-label attributes for both input fields.
- Introduced two new props: `startDateInputAriaLabel` and `endDateInputAriaLabel`, allowing child components to pass custom `aria-label` values for the respective inputs.
- If no `aria-label` is provided through the new props, the aria-label attributes will not be added to the date range picker inputs by default.
https://eightfoldai.atlassian.net/browse/ENG-122300
- Ensure that the aria-label props can be passed to the Date Range Picker component.
- Verify that the aria-label values are correctly …
=> fix: added aria-label to the date range picker

src/components/Dropdown/Dropdown.tsx
Issue When the user navigating through dropdown using shift + tab the focus is moving to the dropdown list container.
Fix: Focus should not be moved on dropdown container, focus should be move to the dropdown items, when we use the tab or shift + tab.
https://eightfoldai.atlassian.net/browse/ENG-118833
1. Open the dropdown
2. Navigate between the dropdown items using tab and shift + tab
3. Observe the dropdown container: focus should not be moved on dropdown container
https://github.com/user-attachments/assets/09753a87-89a4-4a38-9160-365b29ddd499
=> fix: dropdown: fixed dropdown container focus issue

src/components/Inputs/Input.types.ts, src/components/Inputs/TextInput/TextInput.tsx, src/components/Select/Select.tsx
- Added `aria-hidden=true` to select expandable button as it was not passing aria attribute not allowed check from Accessibility insights tool.
- The button was already out of tab order and with role presentation.
Jira task - https://eightfoldai.atlassian.net/browse/ENG-122358
- Go to select component and run Accessibility insights tool and check if there are no `aria-allowed-role` error.
=> a11y: Added aria hidden to expandable button

src/components/DateTimePicker/DatePicker/Generate/generateRangePicker.tsx
The tool  Accessibility Insights for web reports an issue ARIA attributes prohibited for element without any role. To fix this issue a
Removed aria-label attribute from span arrow
https://eightfoldai.atlassian.net/browse/ENG-120721
Search for DateTimePicker component -> check for RangePicker component -> check for separator arrow role 
on route : /events/edit?plannedEventId=xaoNqQjGk0Z
The Date picker arrow under Date and TIme edit section does not report an issue on ARC tool
=> fix: eng-120721 : added role to date picker span tag

src/components/DateTimePicker/DatePicker/Tests/__snapshots__/RangePicker.test.js.snap, src/components/DateTimePicker/Internal/Tests/__snapshots__/range.test.tsx.snap, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/Select/__snapshots__/Select.test.tsx.snap
as role of overlay container is generic but it may not be focusable at all times
changes- so added prop to set tabindex generically as well
N/A
https://eightfoldai.atlassian.net/browse/ENG-99020
CASE: if overlay container is passed to component and  its role is set as presentation then container should not be focusable only options should be focusable
=> fix: dropdown: removed outer container tabindex

src/components/InlineSvg/InlineSvg.test.tsx, src/components/Table/Hooks/useSorter.tsx, src/components/Table/Tests/Table.sorter.test.js, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap
- removed the `role="button"` and other accessibility attributes from `<th>` to its inside `div`
**Issue** was user not able to move to cells which are having buttons, like: `Sorting Button`, `Action button` which you can view in below recording.
https://github.com/user-attachments/assets/4aad86e2-4884-49d8-a079-848a2b8bb6ee
JIRA Tickets:
1. https://eightfoldai.atlassian.net/browse/ENG-126322
2. https://eightfoldai.atlassian.net/browse/ENG-126330
Verify that the user is able to navigate to different cells using table. shortcut keys which are
1.  Win: ctrl+alt+`Arrow keys`
2. Mac: control+option+`Arrow Keys`
**After Implementing the solution**
https://github.com/user-attachments/assets/9e85b7b9-c44f-4a09-ac29-237982c51dc1
=> fix: table cells access using shortcut key

src/components/Table/Hooks/useSorter.tsx
Removing an unused event parameter in the Table Sorter onClick function
https://eightfoldai.atlassian.net/browse/ENG-126322
> This is a lint error
=> fix: remove unused event parameter from Table sorter onClick handler

src/components/Upload/upload.module.scss
- Fix max width on Large dropzone container
- Before vs after
https://eightfoldai.atlassian.net/browse/ENG-126557
- open storybook http://octuple.eightfold-corp.ai/?path=/story/upload--drag-and-drop-single-large
- (large dropzone)
- Upload a file with large name, the name should not overflow
- Before vs after
=> [Fix][TM-oncall]: Upload container max width 100%

src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx, src/components/Menu/MenuItem/MenuItemCustom/MenuItemCustom.tsx, src/components/Menu/MenuItem/MenuItemLink/MenuItemLink.tsx, src/components/Menu/MenuItem/MenuItemSubHeader/MenuItemSubHeader.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap
Roles for select options were set on internal elements enclosed inside the li element. This resulted li interfering with accessibility tools while deducing the aria attributes for the enclosed items as all accessibility were set on enclosed items.
This commit sets the role for enclosing li as presentation.
`role="presentation"` (or equivalently `role="none"`) is an ARIA attribute that indicates an element is being used only for visual presentation and should be ignored by assistive technologies like screen readers. It effectively removes the semantic meaning of the element while keeping its visual appearance and behaviour.
**Before**
**After**
This helps in deducing the aria attributes for the enclosed items correctly.
https://github.com/EightfoldAI/octuple/issues/942 …
=> fix: a11y: Fix role inheritance for select options

src/components/Table/Table.tsx
1. The scrollable buttons announces "Scroll left" and "Scroll right" 
2. Added a function that modifies the aria labels for each row announcing "Scroll {Row header name} left/right"
https://eightfoldai.atlassian.net/browse/ENG-111201
1. Go to the Table, select Fixed columns with Scroller
2. check for the announcement of the scroll right and scroll left buttons
3. Aria-label is associated to each title
https://github.com/user-attachments/assets/41a97522-1b64-4fad-8589-b1585da4873c
=> fix(table): update aria labels, add handleRowHover function

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts
ISSUE - not able to add aria-attributes required to make overlay accessible
fix - added and overlayProp to dropdown and spread it on overlay container
https://eightfoldai.atlassian.net/browse/ENG-130143
1. Verify TypeScript  compilation with new type definitions
2. verify we can pass props to overlay container
3. possible regressions - just spreading props to overlay container so there shouldn't be any regressions
=> feat: dropdown: added overlay props

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.ts, src/components/List/List.tsx, src/components/List/List.types.ts, src/components/Menu/Menu.stories.tsx
Toggle Dropdown on Shift+Tab Behavior & Cyclic Navigation
- Added functionality to toggle dropdown visibility when pressing Shift + Tab.
- Maintains existing Tab behavior while adding Shift + Tab support.
- Provided a way to handle cyclic navigation for menu items.
- Introduced a flag applyCyclicNavigation in the List component:
- When set to `true`, cyclic navigation is enabled.
- When `false` or `unset`, the behavior remains unchanged.
NA
https://eightfoldai.atlassian.net/browse/ENG-118833
**Toggle Dropdown on Shift+Tab**
1. Pass `toggleDropdownOnShiftTab ={false}` to dropdown component
2. Navigate to dropdown button
3. Press Enter
4. Once Dropdown appear Press Shift+Tab
5. Observe Dropdown should close.
https://github.com/user-attachments/assets/54390c0e-27c0-4b51-93d0-b87aa9a1159a …
=> Fix: Close dropdown on Shift + Tab and enable cyclic navigation for menu items.

src/components/Dropdown/Dropdown.tsx
In dropdown component, the dropdown is opened towards top if the space in the downside is less. When the overlay content changes, and say becomes 3 option from 5 options, the starting position is not updated correctly and the results appear towards top at a distance from input bar creating bad user experience 
https://eightfoldai.atlassian.net/browse/ENG-135599
Do a local octuple build and sync with the www/react octuple lib. https://eightfoldai.atlassian.net/wiki/spaces/EP/pages/1812922377/Octuple+Development+Tips+Tricks Follow Alternative approach in this.
Login as demo@eightfolddemo-spradhan.com
Go to resourcing page
Click on create project and type in the program name input.
Before starting to type, open the developer tools window so that to decrease space in the downside area so to …
=> fix(dropdown): recalculate start position when overlaycontent gets updated

src/components/Menu/CascadingMenu.tsx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.test.tsx, src/components/Menu/Menu.types.ts, src/components/Menu/MenuItem/MenuItem.types.ts, src/components/Menu/MenuItem/MenuItemButton/MenuItemButton.tsx
Adding react synthetic event as a second param to onChange handler of Menu Component so that user can stop bubbling.
https://eightfoldai.atlassian.net/browse/ENG-137350
Scenario 1 (event.stopPropogation used)
1. Go to Basic Menu component in storybook
2. Open console and click on any item inside opened menu. 
3. "Click event bubbled to parent" should not be consoled since we've used event.stopPropogation in the storybook component.
Scenatio 2 (event.stopPropogation not used)
1. Go to Link Menu component in storybook
2. Open console and click on any item inside opened menu.
3. "Click event bubbled to parent" should be consoled since we've not used event.stopPropogation in the storybook component.
=> fix: added synthetic mouse event as a second optional param

src/components/Accordion/Accordion.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Fixed added data-testId to the accordian button to fix playwrights
https://eightfoldai.atlassian.net/browse/ENG-110847
Go to accordian component and check if arrow button has data-testId
=> fix: added data-testid to the accordion button

src/components/Dropdown/Dropdown.tsx
Added functionality to close the dropdown when Shift + Tab is pressed while the focus is on the first option, to handle focus loss behavior
NA
https://eightfoldai.atlassian.net/browse/ENG-139569
Pull branch down locally and start storybook (yarn storybook)
Go to dropdown
Make the toggleDropdownOnShiftTab false
Verify whether the dropdown closes when pressing Shift+Tab while the focus is on the first option
https://github.com/user-attachments/assets/146db414-7275-4abd-a8f3-46d5714d6dc9
=> fix: dropdown :added condition to close the dialog on shift tab

src/components/Pills/Pill.tsx, src/components/Pills/Pills.stories.tsx, src/components/Pills/Pills.types.ts
Fixed closeButtonProps from Pill props 
Added support to ariaLabel from closeButtonProps to return pill label 
https://eightfoldai.atlassian.net/browse/ENG-141606
Open storybook 
Open story of Pill -> Closable 
Check the aria-label of Closable Button
=> Fixed closeButton props from pill to return pill label from ariaLabel

src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/components/Skill/Tests/__snapshots__/SkillBlock.test.tsx.snap, src/components/Table/Tests/__snapshots__/Table.sorter.test.js.snap, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx
A11y fix: 
Only add `aria-describedby` on a tooltip reference element when the tooltip is visible. When the tooltip is not visible the tooltip element is not in DOM and hence the reference is broken.
https://eightfoldai.atlassian.net/browse/ENG-141226
1. Go to storybook for multi select. /?path=/story/select--multiple
2. Select the long text item which will be showing tooltips.
3. Verify that there is no ARC toolkit error for invalid aria-describedby.
4. Hover over a pill to show its tooltip, and while the tooltip is visible, verify that aria-describedby is set on the reference element.
5. [Regression test]: Verify that tooltip hover in/out works fine.
=> fix: remove non existent tooltip aria-describedby reference

src/components/Stepper/Stepper.tsx, src/components/Stepper/Tests/__snapshots__/Stepper.test.tsx.snap
added aria-current="step" for stepper component
https://eightfoldai.atlassian.net/browse/ENG-139790
- added aria-current="step" for current active step
- check if default active step have aria-current="step"
- check if aria-current is added only when step is active and not for other steps
=> fix: stepper: added aria-current

src/components/Select/select.module.scss
Fixed horizontal overflow issue when selecting multiple values in select component
https://eightfoldai.atlassian.net/browse/ENG-139762
1. /?path=/story/select--multiple
2. select 5-6 pills in multi select
3. There should be no horizontal scroll in mobile screen
6. Verify step 3 by doing the same on https://eightfoldai.github.io/octuple.github.io/iframe.html?id=select--multiple&viewMode=story (You will observe horizontal scroll on mobile screen)
=> fix: overflow issue

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
Meaningful label:
Instead of “+1”, screen reader should read it as “and 1 more option(s) selected”.
Semantic Control:
On Enter/Space/Clicking “+1”, select should open with the focus on the first item of select menu
https://eightfoldai.atlassian.net/browse/ENG-136058
1. /?path=/story/select--multiple
2. turn on voice mode
3. Focus on +1 button
4. Meaning label (announce button and "more options selected")
5. Click/"Enter"/"Space" while +1 button is focus, it should open the dropdown and focus on first element.
=> fix: more button a11y fixes

src/components/Pills/Pill.tsx, src/components/Pills/__snapshots__/Pill.test.tsx.snap, src/components/Select/__snapshots__/Select.test.tsx.snap
vscode npm test failed because of https://github.com/EightfoldAI/octuple/pull/981/files
https://eightfoldai.atlassian.net/browse/ENG-141606
=> fix: getAriaLabel check before use

src/components/Stepper/Stepper.tsx, src/components/Stepper/Tests/__snapshots__/Stepper.test.tsx.snap
Reverts EightfoldAI/octuple#974
the fix may cause regression for many steppers where aria-current is alredy defined in child components instead of <li tag
=> Revert "fix: stepper: added aria-current"

src/components/Select/Select.tsx, src/components/Select/Select.types.ts
Semantic Control:
Fixed an issue where if tabIndex=-1 was added to pillProps then +n button was not controllable.
Fix: Added keepCountPillFocus=true as a default prop to Select
https://eightfoldai.atlassian.net/browse/ENG-136058
=> fix: plus n button focus will be on by default

src/components/Icon/Icon.tsx, src/components/Icon/Icon.types.ts
This PR adds support for passing a custom role to the MdiIcon component through the `iconRole` prop. This allows for better accessibility customization of icons when needed.
NA
https://eightfoldai.atlassian.net/browse/ENG-138365
- Verify TypeScript compilation with new type definitions.
- Verify we can pass props to the MdiIcon (SVG) component.
=> fix: icon: Add role prop support to MdiIcon component

src/components/InfoBar/InfoBar.tsx, src/components/Snackbar/SnackbarContainer.tsx, src/components/Snackbar/snack.ts
- Focus was being set on a snackbar without a close option.
- Added condition to only move focus to snackbar when it is closable.
- pull branch down locally and start storybook (yarn storybook)
- go to Snackbar.
- Verify that the focus does not move to the snackbar container when closable : false .
- Set closable to true in the controls.
- Ensure that focus shifts to the toast message when it appears.
- Verify that pressing the Tab key moves the focus to the close button
https://github.com/user-attachments/assets/d550e6e8-7a22-4d17-a509-39d1ba5469a4
**Steps for Regression:**
**1. When closable: true**
**Expected Behavior:**
- Focus should move to the snackbar when it appears.
- Upon dismissal, focus should return to the element that triggered the snackbar.
- If the triggering element is …
=> fix: snackbar: fixed focus for snackbar

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
Aria label was not exposed to input of the select component. In order to do that couple of changes are made:
1. Select component accepts aria-label props
2. passed that prop value to TextInput component
https://eightfoldai.atlassian.net/browse/IMPL-188353
=> fix: select input will have ariaLabel

CLAUDE.md, src/components/DateTimePicker/DatePicker/DatePicker.stories.tsx, src/components/DateTimePicker/DatePicker/Generate/generateRangePicker.tsx, src/components/DateTimePicker/DatePicker/Styles/mixins.scss, src/components/DateTimePicker/Internal/Hooks/useCellProps.ts, src/components/DateTimePicker/Internal/Locale/en_US.ts, src/components/DateTimePicker/Internal/OcPicker.tsx, src/components/DateTimePicker/Internal/OcPicker.types.ts, src/components/DateTimePicker/Internal/OcPickerPartial.tsx, src/components/DateTimePicker/Internal/OcRangePicker.tsx, src/components/DateTimePicker/Internal/Partials/DatePartial/DateBody.tsx, src/components/DateTimePicker/Internal/Tests/__snapshots__/picker.test.tsx.snap, src/components/DateTimePicker/Internal/Tests/accessibility.test.tsx, src/components/DateTimePicker/Internal/Tests/range.test.tsx, src/components/DateTimePicker/Internal/ocpicker.module.scss, src/components/DateTimePicker/claude.md
This PR implements two key accessibility improvements for the DateTimePicker Range Picker component:
- Added `trapFocus` prop support to `OcRangePicker` (defaults to `false` to prevent regressions)
- Implemented `FocusTrap` component wrapper when enabled
- Added proper keyboard handling (Escape key) and mouse event prevention
- Updated range picker generator to pass through `trapFocus` prop
- **Root Issue**: Range picker focus remained stuck on header elements when navigating with arrow keys, preventing proper date announcements for screen readers
- **Root Cause**: `useCellProps` hook returned `undefined` for range pickers, disabling focus management on date cells
- **Solution**: Modified `useCellProps` to always return cell props, enabling proper focus shifts to date cells
- **Added …
=> feat(DatePicker): add accessibility announcement for arrow key navigation
